export const dashboardLabels: Record<string, string> = {
  'kpi.pendingOrders': 'Bekleyen sipariş',
  'kpi.activeShipments': 'Aktif gönderi',
  'kpi.delivered': 'Teslim edilen',
  'kpi.openQuotes': 'Açık teklif',
  'quick.createShipment.title': 'Gönderi Oluştur',
  'quick.createShipment.description': 'Yeni kargo veya lojistik gönderisi başlatın',
  'quick.connectChannel.title': 'Satış Kanalını Bağla',
  'quick.connectChannel.description': 'Siparişleriniz otomatik aktarılsın',
  'quick.priceCalculation.title': 'Teklif al',
  'quick.priceCalculation.description': 'Talebini oluştur, Gönder uygun seçenekleri bulsun',
  'quick.excelBulk.title': 'Excel ile toplu oluştur',
  'quick.excelBulk.description': 'Toplu siparişleri şablonla yükleyin',
  'wallet.title': 'Cüzdan özeti',
  'wallet.balance': 'Bakiye',
  'wallet.topUp': 'Bakiye yükle',
  'wallet.lastMovement': 'Son hareket',
  'wallet.loading': 'Cüzdan yükleniyor…',
  'wallet.emptyMovement': 'Henüz hareket yok',
  'perf.title': 'Performans özeti',
  'perf.shipments': 'Gönderi',
  'perf.revenue': 'Ciro',
  'perf.deliveryRate': 'Teslim oranı',
  'perf.avgCost': 'Ort. maliyet',
  'perf.reports': 'Raporlar',
  'perf.period7d': 'Son 7 gün',
  'perf.period30d': 'Son 30 gün',
  'perf.range7d': '7g',
  'perf.range30d': '30g',
  'perf.range3m': '3a',
  'perf.chartAvg': 'Ortalama',
  'insights.title': 'Analitik özeti',
  'insights.volume': 'Gönderi hacmi',
  'insights.status': 'Teslimat durumu',
  'insights.reports': 'Raporlar',
  'insights.range7d': '7g',
  'insights.range30d': '30g',
  'insights.range3m': '3a',
  'action.orders.title': 'Yeni siparişler',
  'action.orders.description': 'Onay veya işlem bekleyen siparişler',
  'action.orders.cta': 'Siparişlere git',
  'action.quotes.title': 'Yeni teklifler',
  'action.quotes.description': 'Yanıt veya aksiyon bekleyen teklifler',
  'action.quotes.cta': 'Tekliflere git',
  'status.pending': 'Bekliyor',
  'status.in_transit': 'Yolda',
  'status.delivered': 'Teslim',
  'status.issue': 'Sorunlu',
  'integration.connected': 'Bağlı',
  'integration.warning': 'Uyarı',
  'integration.disconnected': 'Bağlı değil',
  'updates.shipmentDelivered': 'GND-1005 teslim edildi',
  'updates.quoteWaiting': 'Teklif TKF-88 yanıt bekliyor',
  'updates.integrationWarning': 'ERP entegrasyonunda uyarı var',
}

export function tDashboard(key: string): string {
  return dashboardLabels[key] ?? key
}
