import type { SalesChannelCatalogItem, SalesChannelId } from '../_types/sales-channels'

export const SALES_CHANNELS_CATALOG: SalesChannelCatalogItem[] = [
  {
    id: 'trendyol',
    name: 'Trendyol',
    category: 'marketplace',
    description: 'Trendyol satıcı panelinden siparişleri otomatik alın.',
    help: 'Satıcı paneli → Entegrasyon bilgileri altındaki satıcı ID, API Key ve API Secret değerlerini girin.',
    logoSrc: '/gonder/channels/trendyol.svg',
    accentClass: 'bg-[#F27A1A]/15 text-[#F27A1A]',
    initials: 'T',
    fields: [
      {
        key: 'sellerId',
        label: 'Satıcı ID',
        type: 'text',
        placeholder: 'Örn. 123456',
        required: true,
      },
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'text',
        placeholder: 'Trendyol API anahtarı',
        required: true,
      },
      {
        key: 'apiSecret',
        label: 'API Secret',
        type: 'password',
        placeholder: 'Trendyol API gizli anahtarı',
        required: true,
      },
      {
        key: 'webhookUrl',
        label: 'Webhook URL (opsiyonel)',
        type: 'url',
        placeholder: 'https://ornek.com/webhooks/trendyol',
        hint: 'Sipariş bildirimlerini almak için kendi endpoint’iniz.',
        fullWidth: true,
      },
    ],
  },
  {
    id: 'hepsiburada',
    name: 'Hepsiburada',
    category: 'marketplace',
    description: 'Merchant hesabınızdan sipariş ve kargo etiketlerini senkronlayın.',
    help: 'Hepsiburada Entegrasyon / OMS panelindeki merchant ID ve secret key bilgilerini kullanın.',
    logoSrc: '/gonder/channels/hepsiburada.svg',
    accentClass: 'bg-[#FF6000]/15 text-[#FF6000]',
    initials: 'H',
    fields: [
      {
        key: 'merchantId',
        label: 'Merchant ID',
        type: 'text',
        placeholder: 'Örn. hb-merchant-001',
        required: true,
      },
      {
        key: 'secretKey',
        label: 'Secret Key',
        type: 'password',
        placeholder: 'Hepsiburada gizli anahtar',
        required: true,
      },
      {
        key: 'serviceKey',
        label: 'Servis anahtarı',
        type: 'text',
        placeholder: 'Integrator / service key',
        required: true,
      },
      {
        key: 'userAgent',
        label: 'User-Agent',
        type: 'text',
        placeholder: 'ARF_Gonder_1.0',
        hint: 'Hepsiburada API çağrılarında kullanılan uygulama adı.',
      },
    ],
  },
  {
    id: 'amazon',
    name: 'Amazon',
    category: 'marketplace',
    description: 'Amazon TR (SP-API) üzerinden siparişleri Gönder’e aktarın.',
    help: 'Seller Central → Apps & Services altındaki SP-API kimliklerini girin. Pazar yeri TR: A33AVAJ2PDY3EV.',
    logoSrc: '/gonder/channels/amazon.svg',
    accentClass: 'bg-[#FF9900]/15 text-[#E47911]',
    initials: 'A',
    fields: [
      {
        key: 'sellerId',
        label: 'Seller ID',
        type: 'text',
        placeholder: 'Örn. A1ARFDEMOXYZ',
        required: true,
      },
      {
        key: 'marketplaceId',
        label: 'Marketplace ID',
        type: 'text',
        placeholder: 'A33AVAJ2PDY3EV',
        hint: 'Amazon.com.tr varsayılan pazar yeri kodu.',
        required: true,
      },
      {
        key: 'accessKey',
        label: 'Access Key',
        type: 'text',
        placeholder: 'AKIA…',
        required: true,
      },
      {
        key: 'secretKey',
        label: 'Secret Key',
        type: 'password',
        placeholder: 'Amazon gizli anahtar',
        required: true,
      },
      {
        key: 'roleArn',
        label: 'IAM Role ARN (opsiyonel)',
        type: 'text',
        placeholder: 'arn:aws:iam::123456789012:role/SellingPartner',
        fullWidth: true,
      },
    ],
  },
  {
    id: 'n11',
    name: 'N11',
    category: 'marketplace',
    description: 'N11 mağazanızdaki siparişleri Gönder paneline bağlayın.',
    help: 'N11 satıcı paneli → API Yönetimi ekranından uygulama anahtarlarını kopyalayın.',
    logoSrc: '/gonder/channels/n11.svg',
    accentClass: 'bg-[#7B1FA2]/15 text-[#7B1FA2]',
    initials: 'N',
    fields: [
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'text',
        placeholder: 'N11 API anahtarı',
        required: true,
      },
      {
        key: 'apiSecret',
        label: 'API Secret',
        type: 'password',
        placeholder: 'N11 API gizli anahtarı',
        required: true,
      },
      {
        key: 'appKey',
        label: 'Uygulama anahtarı (opsiyonel)',
        type: 'text',
        placeholder: 'N11 app key',
      },
    ],
  },
  {
    id: 'shopify',
    name: 'Shopify',
    category: 'storefront',
    description: 'Shopify mağazanızdaki siparişleri webhook ile senkronlayın.',
    help: 'Shopify Admin → Ayarlar → Uygulamalar ve satış kanalları → Geliştirici uygulaması ile Admin API access token oluşturun.',
    logoSrc: '/gonder/channels/shopify.svg',
    accentClass: 'bg-[#95BF47]/15 text-[#5E8E3E]',
    initials: 'S',
    fields: [
      {
        key: 'storeUrl',
        label: 'Mağaza URL',
        type: 'url',
        placeholder: 'https://magazaniz.myshopify.com',
        required: true,
        fullWidth: true,
      },
      {
        key: 'accessToken',
        label: 'Admin API access token',
        type: 'password',
        placeholder: 'shpat_…',
        required: true,
        fullWidth: true,
      },
      {
        key: 'webhookSecret',
        label: 'Webhook secret (opsiyonel)',
        type: 'password',
        placeholder: 'Shopify webhook imza anahtarı',
        fullWidth: true,
      },
    ],
  },
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    category: 'storefront',
    description: 'WordPress / WooCommerce mağazanızdaki siparişleri REST API ile alın.',
    help: 'WooCommerce → Ayarlar → Gelişmiş → REST API üzerinden Consumer Key ve Secret oluşturun.',
    logoSrc: '/gonder/channels/woocommerce.svg',
    accentClass: 'bg-[#96588A]/15 text-[#96588A]',
    initials: 'W',
    fields: [
      {
        key: 'siteUrl',
        label: 'Site URL',
        type: 'url',
        placeholder: 'https://magazaniz.com',
        required: true,
        fullWidth: true,
      },
      {
        key: 'consumerKey',
        label: 'Consumer Key',
        type: 'text',
        placeholder: 'ck_…',
        required: true,
      },
      {
        key: 'consumerSecret',
        label: 'Consumer Secret',
        type: 'password',
        placeholder: 'cs_…',
        required: true,
      },
    ],
  },
  {
    id: 'ikas',
    name: 'İkas',
    category: 'storefront',
    description: 'İkas vitrininizdeki siparişleri Gönder’e aktarın.',
    help: 'İkas panel → Uygulamalar / API erişimi altındaki mağaza slug ve anahtarları kullanın.',
    logoSrc: '/gonder/channels/ikas.svg',
    accentClass: 'bg-[#0D9488]/15 text-[#0D9488]',
    initials: 'İ',
    fields: [
      {
        key: 'storeSlug',
        label: 'Mağaza slug',
        type: 'text',
        placeholder: 'magazaniz',
        hint: 'ikas.com üzerindeki mağaza kısa adı.',
        required: true,
      },
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'text',
        placeholder: 'İkas API anahtarı',
        required: true,
      },
      {
        key: 'apiSecret',
        label: 'API Secret',
        type: 'password',
        placeholder: 'İkas API gizli anahtarı',
        required: true,
      },
    ],
  },
  {
    id: 'tsoft',
    name: 'T-Soft',
    category: 'storefront',
    description: 'T-Soft e-ticaret panelinizden sipariş aktarımı.',
    help: 'T-Soft yönetim paneli kullanıcı bilgileri ve mağaza adresi ile bağlanır.',
    logoSrc: '/gonder/channels/tsoft.svg',
    accentClass: 'bg-[#1B4F9C]/15 text-[#1B4F9C]',
    initials: 'TS',
    fields: [
      {
        key: 'storeUrl',
        label: 'Mağaza URL',
        type: 'url',
        placeholder: 'https://www.magazaniz.com',
        required: true,
        fullWidth: true,
      },
      {
        key: 'username',
        label: 'Kullanıcı adı',
        type: 'text',
        placeholder: 'entegrasyon-kullanici',
        required: true,
      },
      {
        key: 'password',
        label: 'Şifre',
        type: 'password',
        placeholder: 'Panel şifresi',
        required: true,
      },
      {
        key: 'warehouseCode',
        label: 'Depo kodu (opsiyonel)',
        type: 'text',
        placeholder: 'DEPO-01',
      },
    ],
  },
  {
    id: 'ideasoft',
    name: 'Ideasoft',
    category: 'storefront',
    description: 'Ideasoft mağazanızdaki siparişleri REST servisi ile bağlayın.',
    help: 'Ideasoft yönetim paneli → Web servisleri bölümünden kullanıcı ve API anahtarını alın.',
    logoSrc: '/gonder/channels/ideasoft.svg',
    accentClass: 'bg-[#E85D04]/15 text-[#E85D04]',
    initials: 'ID',
    fields: [
      {
        key: 'storeUrl',
        label: 'Mağaza URL',
        type: 'url',
        placeholder: 'https://www.magazaniz.com',
        required: true,
        fullWidth: true,
      },
      {
        key: 'username',
        label: 'Web servis kullanıcısı',
        type: 'text',
        placeholder: 'api-user',
        required: true,
      },
      {
        key: 'apiKey',
        label: 'API Key',
        type: 'password',
        placeholder: 'Ideasoft API anahtarı',
        required: true,
      },
    ],
  },
  {
    id: 'xml-csv',
    name: 'Özel XML / CSV',
    category: 'feed',
    description: 'Kendi sipariş feed’inizi (XML veya CSV) periyodik olarak çekin.',
    help: 'Feed URL’si, kimlik bilgileri ve isteğe bağlı webhook ile özel kaynakları bağlayın.',
    logoSrc: '/gonder/channels/xml-csv.svg',
    accentClass: 'bg-slate-500/15 text-slate-600',
    initials: 'XML',
    fields: [
      {
        key: 'feedUrl',
        label: 'Feed URL',
        type: 'url',
        placeholder: 'https://ornek.com/orders.xml',
        required: true,
        fullWidth: true,
      },
      {
        key: 'format',
        label: 'Format',
        type: 'select',
        required: true,
        options: [
          { value: 'xml', label: 'XML' },
          { value: 'csv', label: 'CSV' },
        ],
      },
      {
        key: 'pollMinutes',
        label: 'Çekim aralığı (dk)',
        type: 'text',
        placeholder: '15',
        hint: 'Feed’in kaç dakikada bir yenileneceği.',
      },
      {
        key: 'username',
        label: 'Kullanıcı adı (opsiyonel)',
        type: 'text',
        placeholder: 'feed-user',
      },
      {
        key: 'password',
        label: 'Şifre (opsiyonel)',
        type: 'password',
        placeholder: 'Feed şifresi',
      },
      {
        key: 'webhookUrl',
        label: 'Webhook URL (opsiyonel)',
        type: 'url',
        placeholder: 'https://ornek.com/webhooks/orders',
        fullWidth: true,
      },
    ],
  },
]

const CATALOG_BY_ID = new Map(SALES_CHANNELS_CATALOG.map((item) => [item.id, item]))

export function getSalesChannelById(id: string): SalesChannelCatalogItem | null {
  return CATALOG_BY_ID.get(id as SalesChannelId) ?? null
}

export function isSalesChannelId(id: string): id is SalesChannelId {
  return CATALOG_BY_ID.has(id as SalesChannelId)
}
