export type {
  SupplierDetail,
  SupplierVehicle,
  SupplierVehicleDocument,
  SupplierDriver,
  DriverDocument,
  SupplierDocument,
  VehicleType,
  VehicleStatus,
  VehicleBodyType,
  VehicleDocumentType,
  LicenseClass,
  DriverStatus,
  SrcType,
  BloodGroup,
  DriverDocumentType,
  DocumentType,
  SupplierTransportRecord,
  SupplierTransportDurum,
  SupplierTransportYukSatir,
  SupplierFinancialRecord,
  SupplierInvoicePaymentStatus,
  SupplierExstreType,
} from "./supplier-detail-types"
