import { SEED_GEO } from './seed'
import type {
  CourierCostAssignment,
  CourierCostList,
  CourierEarningsSnapshot,
  CourierPayoutLedger,
  CourierPayoutTerms,
  EmploymentTypeCostDefault,
  PayoutEntry,
} from '../_types'

const now = '2026-08-07T10:00:00.000Z'

export function buildSeedCourierCostLists(): CourierCostList[] {
  return [
    {
      id: 'ccl_km_default',
      code: 'KURYE-KM-2026',
      name: 'Kurye Km Tarifesi',
      description: 'Varsayılan tarife — km + desi bantları.',
      isDefault: true,
      status: 'active',
      currency: 'TRY',
      distanceStructure: 'km',
      quantityBasis: 'desi',
      compensationModel: 'tariff',
      validFrom: '2026-01-01',
      createdAt: now,
      updatedAt: now,
      createdBy: 'sistem',
      rules: [
        {
          id: 'ccr_km_fixed',
          costListId: 'ccl_km_default',
          name: '1–5 desi sabit',
          priority: 80,
          status: 'active',
          pricingMode: 'base_plus_km',
          desiPricing: 'fixed',
          desiStart: 1,
          desiEnd: 5,
          flatFee: 55,
          perKm: 3.25,
          minFee: 70,
        },
        {
          id: 'ccr_km_dyn',
          costListId: 'ccl_km_default',
          name: '6–20 desi dinamik',
          priority: 60,
          status: 'active',
          pricingMode: 'base_plus_km',
          desiPricing: 'dynamic',
          desiStart: 6,
          desiEnd: 20,
          baseFee: 40,
          perDesi: 6,
          perKm: 3.25,
          minFee: 85,
        },
      ],
    },
    {
      id: 'ccl_od',
      code: 'KURYE-OD-2026',
      name: 'Çıkış–Varış Tarifesi',
      description: 'İlçe çifti + desi aralığı.',
      isDefault: false,
      status: 'active',
      currency: 'TRY',
      distanceStructure: 'od',
      quantityBasis: 'desi',
      compensationModel: 'tariff',
      validFrom: '2026-02-01',
      createdAt: now,
      updatedAt: now,
      createdBy: 'sistem',
      rules: [
        {
          id: 'ccr_od_fixed',
          costListId: 'ccl_od',
          name: 'Ataşehir → Tuzla · 1–5',
          priority: 100,
          status: 'active',
          pricingMode: 'od_district',
          desiPricing: 'fixed',
          desiStart: 1,
          desiEnd: 5,
          flatFee: 95,
          origin: {
            cityId: SEED_GEO.istanbul.cityId,
            cityName: SEED_GEO.istanbul.cityName,
            districtId: SEED_GEO.atasehir.districtId,
            districtName: SEED_GEO.atasehir.districtName,
          },
          destination: {
            cityId: SEED_GEO.istanbul.cityId,
            cityName: SEED_GEO.istanbul.cityName,
            districtId: SEED_GEO.tuzla.districtId,
            districtName: SEED_GEO.tuzla.districtName,
          },
        },
        {
          id: 'ccr_od_dyn',
          costListId: 'ccl_od',
          name: 'Ataşehir → Tuzla · 6–15',
          priority: 80,
          status: 'active',
          pricingMode: 'od_district',
          desiPricing: 'dynamic',
          desiStart: 6,
          desiEnd: 15,
          baseFee: 50,
          perDesi: 10,
          minFee: 110,
          origin: {
            cityId: SEED_GEO.istanbul.cityId,
            cityName: SEED_GEO.istanbul.cityName,
            districtId: SEED_GEO.atasehir.districtId,
            districtName: SEED_GEO.atasehir.districtName,
          },
          destination: {
            cityId: SEED_GEO.istanbul.cityId,
            cityName: SEED_GEO.istanbul.cityName,
            districtId: SEED_GEO.tuzla.districtId,
            districtName: SEED_GEO.tuzla.districtName,
          },
        },
      ],
    },
    {
      id: 'ccl_zone',
      code: 'KURYE-BOLGE-2026',
      name: 'Bölge Tarifesi',
      description: 'Varış bölgesi + desi.',
      isDefault: false,
      status: 'active',
      currency: 'TRY',
      distanceStructure: 'zone',
      quantityBasis: 'desi',
      compensationModel: 'tariff',
      validFrom: '2026-02-01',
      createdAt: now,
      updatedAt: now,
      createdBy: 'sistem',
      rules: [
        {
          id: 'ccr_zone_fixed',
          costListId: 'ccl_zone',
          name: 'Doğu bölge · 1–8',
          priority: 80,
          status: 'active',
          pricingMode: 'zone_flat',
          desiPricing: 'fixed',
          desiStart: 1,
          desiEnd: 8,
          flatFee: 85,
          zoneId: 'zone_asya_dogu',
        },
        {
          id: 'ccr_zone_dyn',
          costListId: 'ccl_zone',
          name: 'Doğu bölge · 9–25',
          priority: 60,
          status: 'active',
          pricingMode: 'zone_flat',
          desiPricing: 'dynamic',
          desiStart: 9,
          desiEnd: 25,
          baseFee: 60,
          perDesi: 7,
          minFee: 100,
          zoneId: 'zone_asya_dogu',
        },
      ],
    },
    {
      id: 'ccl_pkg_tariff',
      code: 'KURYE-PAKET-2026',
      name: 'Paket Başı Tarife',
      description: 'Paket adedi bandı — sabit veya birim ücret.',
      isDefault: false,
      status: 'active',
      currency: 'TRY',
      distanceStructure: 'od',
      quantityBasis: 'package',
      compensationModel: 'tariff',
      validFrom: '2026-03-01',
      createdAt: now,
      updatedAt: now,
      createdBy: 'sistem',
      rules: [
        {
          id: 'ccr_pkg_fixed',
          costListId: 'ccl_pkg_tariff',
          name: '1–3 paket sabit',
          priority: 90,
          status: 'active',
          pricingMode: 'od_district',
          desiPricing: 'fixed',
          desiStart: 0,
          desiEnd: 999,
          packageStart: 1,
          packageEnd: 3,
          flatFee: 75,
          origin: {
            cityId: SEED_GEO.istanbul.cityId,
            cityName: SEED_GEO.istanbul.cityName,
            districtId: SEED_GEO.atasehir.districtId,
            districtName: SEED_GEO.atasehir.districtName,
          },
          destination: {
            cityId: SEED_GEO.istanbul.cityId,
            cityName: SEED_GEO.istanbul.cityName,
            districtId: SEED_GEO.tuzla.districtId,
            districtName: SEED_GEO.tuzla.districtName,
          },
        },
        {
          id: 'ccr_pkg_dyn',
          costListId: 'ccl_pkg_tariff',
          name: '4–10 paket dinamik',
          priority: 70,
          status: 'active',
          pricingMode: 'od_district',
          desiPricing: 'dynamic',
          desiStart: 0,
          desiEnd: 999,
          packageStart: 4,
          packageEnd: 10,
          baseFee: 40,
          perPackage: 18,
          minFee: 90,
          origin: {
            cityId: SEED_GEO.istanbul.cityId,
            cityName: SEED_GEO.istanbul.cityName,
            districtId: SEED_GEO.atasehir.districtId,
            districtName: SEED_GEO.atasehir.districtName,
          },
          destination: {
            cityId: SEED_GEO.istanbul.cityId,
            cityName: SEED_GEO.istanbul.cityName,
            districtId: SEED_GEO.tuzla.districtId,
            districtName: SEED_GEO.tuzla.districtName,
          },
        },
      ],
    },
    {
      id: 'ccl_pkg_hybrid',
      code: 'KURYE-PAKET-KM',
      name: 'Paket + Km',
      description: 'Paket bandı ücreti + km başına ek.',
      isDefault: false,
      status: 'active',
      currency: 'TRY',
      distanceStructure: 'zone',
      quantityBasis: 'package',
      compensationModel: 'hybrid',
      validFrom: '2026-03-01',
      createdAt: now,
      updatedAt: now,
      createdBy: 'sistem',
      rules: [
        {
          id: 'ccr_pkg_km',
          costListId: 'ccl_pkg_hybrid',
          name: '1–5 paket + km',
          priority: 80,
          status: 'active',
          pricingMode: 'zone_flat',
          desiPricing: 'fixed',
          desiStart: 0,
          desiEnd: 999,
          packageStart: 1,
          packageEnd: 5,
          flatFee: 50,
          perKm: 2.5,
          zoneId: 'zone_asya_dogu',
        },
      ],
    },
    {
      id: 'ccl_salary_bonus',
      code: 'KURYE-MAAS-PRIM',
      name: 'Maaşlı (+ prim)',
      description: 'Sabit aylık maaş; opsiyonel km primi.',
      isDefault: false,
      status: 'active',
      currency: 'TRY',
      distanceStructure: 'km',
      quantityBasis: 'desi',
      compensationModel: 'salary_plus_bonus',
      fixedSalaryMonthly: 28500,
      validFrom: '2026-01-01',
      createdAt: now,
      updatedAt: now,
      createdBy: 'sistem',
      rules: [
        {
          id: 'ccr_bonus_km',
          costListId: 'ccl_salary_bonus',
          name: 'Km primi · tüm desi',
          priority: 80,
          status: 'active',
          pricingMode: 'base_plus_km',
          desiPricing: 'dynamic',
          desiStart: 0,
          desiEnd: 999,
          baseFee: 0,
          perDesi: 0,
          perKm: 1.5,
          minFee: 12,
        },
      ],
    },
  ]
}

export function buildSeedCourierCostAssignments(): CourierCostAssignment[] {
  return [
    {
      courierId: 'seed-courier-1',
      costListId: 'ccl_km_default',
      effectiveFrom: '2026-01-01',
      updatedAt: now,
    },
    {
      courierId: 'seed-courier-2',
      costListId: 'ccl_salary_bonus',
      effectiveFrom: '2026-03-01',
      updatedAt: now,
    },
  ]
}

export function buildSeedEmploymentDefaults(): EmploymentTypeCostDefault[] {
  return [
    {
      employmentType: 'esnaf',
      costListId: 'ccl_km_default',
      updatedAt: now,
    },
    {
      employmentType: 'sirket',
      costListId: 'ccl_salary_bonus',
      updatedAt: now,
    },
  ]
}

export function buildSeedCourierPayoutTerms(): CourierPayoutTerms[] {
  return [
    {
      courierId: 'seed-courier-1',
      payoutCycle: 'weekly',
      weeklyPayoutDay: 5,
      creditDays: 0,
      notes: 'Her Cuma hakediş ödemesi',
      updatedAt: now,
    },
    {
      courierId: 'seed-courier-2',
      payoutCycle: 'monthly_fixed_day',
      monthlyPayoutDay: 5,
      creditDays: 3,
      notes: 'Her ayın 5. günü + 3 gün vade',
      updatedAt: now,
    },
  ]
}

export function buildSeedCourierEarnings(): CourierEarningsSnapshot[] {
  return [
    {
      id: 'earn_1',
      orderId: 'lm-1001',
      courierId: 'seed-courier-1',
      courierName: 'Ahmet Yılmaz',
      costListId: 'ccl_km_default',
      costListName: 'Kurye Km Tarifesi',
      matchedRuleId: 'ccr_km_fixed',
      matchedRuleLabel: '1–5 desi sabit',
      pricingMode: 'base_plus_km',
      breakdown: {
        baseFee: 0,
        distanceFee: 58.5,
        desiFee: 0,
        flatFee: 55,
        salaryPortion: 0,
        bonusPortion: 0,
        adjustments: [],
        subtotal: 113.5,
        total: 113.5,
      },
      currency: 'TRY',
      calculatedAt: now,
      earnedAt: '2026-08-04',
    },
    {
      id: 'earn_2',
      orderId: 'lm-1002',
      courierId: 'seed-courier-1',
      courierName: 'Ahmet Yılmaz',
      costListId: 'ccl_km_default',
      costListName: 'Kurye Km Tarifesi',
      matchedRuleId: 'ccr_km_dyn',
      matchedRuleLabel: '6–20 desi dinamik',
      pricingMode: 'base_plus_km',
      breakdown: {
        baseFee: 40,
        distanceFee: 58.5,
        desiFee: 48,
        flatFee: 0,
        salaryPortion: 0,
        bonusPortion: 0,
        adjustments: [],
        subtotal: 146.5,
        total: 146.5,
      },
      currency: 'TRY',
      calculatedAt: now,
      earnedAt: '2026-08-05',
    },
    {
      id: 'earn_3',
      orderId: 'lm-1007',
      courierId: 'seed-courier-2',
      courierName: 'Ayşe Demir',
      costListId: 'ccl_salary_bonus',
      costListName: 'Maaşlı (+ prim)',
      matchedRuleId: 'ccr_bonus_km',
      matchedRuleLabel: 'Km primi · tüm desi',
      pricingMode: 'base_plus_km',
      breakdown: {
        baseFee: 0,
        distanceFee: 27,
        desiFee: 0,
        flatFee: 0,
        salaryPortion: 0,
        bonusPortion: 27,
        adjustments: [],
        subtotal: 27,
        total: 27,
      },
      currency: 'TRY',
      calculatedAt: now,
      earnedAt: '2026-08-03',
    },
  ]
}

export function buildSeedCourierPayoutLedgers(): CourierPayoutLedger[] {
  return [
    {
      id: 'led_1',
      courierId: 'seed-courier-1',
      courierName: 'Ahmet Yılmaz',
      earningsIds: ['earn_1', 'earn_2'],
      amountDue: 260,
      amountPaid: 0,
      payoutStatus: 'bekliyor',
      dueDate: '2026-08-08',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'led_2',
      courierId: 'seed-courier-2',
      courierName: 'Ayşe Demir',
      earningsIds: ['earn_3'],
      amountDue: 27,
      amountPaid: 27,
      payoutStatus: 'odendi',
      dueDate: '2026-08-08',
      paidAt: '2026-08-06',
      method: 'havale',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'led_3',
      courierId: 'seed-courier-2',
      courierName: 'Ayşe Demir',
      earningsIds: [],
      amountDue: 28500,
      amountPaid: 0,
      payoutStatus: 'gecikti',
      dueDate: '2026-07-08',
      note: 'Temmuz maaş hakedişi',
      createdAt: now,
      updatedAt: now,
    },
  ]
}

export function buildSeedPayoutEntries(): PayoutEntry[] {
  return [
    {
      id: 'pay_1',
      courierId: 'seed-courier-2',
      courierName: 'Ayşe Demir',
      ledgerId: 'led_2',
      amount: 27,
      method: 'havale',
      paidAt: '2026-08-06',
      note: 'Km primi ödemesi',
      createdBy: 'sistem',
      createdAt: now,
    },
  ]
}
