/**
 * Mock Data for DataTable Testing
 */

export interface User {
  id: string
  name: string
  email: string
  role: 'Admin' | 'User' | 'Manager' | 'Developer'
  status: 'Active' | 'Inactive' | 'Pending'
  department: string
  joinDate: string
  salary: number
}

export interface Product {
  id: string
  name: string
  category: string
  price: number
  stock: number
  status: 'In Stock' | 'Out of Stock' | 'Low Stock'
  rating: number
  brand: string
}

// Mock Users Data
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Ahmet Yılmaz',
    email: 'ahmet.yilmaz@example.com',
    role: 'Admin',
    status: 'Active',
    department: 'IT',
    joinDate: '2022-01-15',
    salary: 85000,
  },
  {
    id: '2',
    name: 'Ayşe Demir',
    email: 'ayse.demir@example.com',
    role: 'Manager',
    status: 'Active',
    department: 'Sales',
    joinDate: '2021-06-20',
    salary: 75000,
  },
  {
    id: '3',
    name: 'Mehmet Kaya',
    email: 'mehmet.kaya@example.com',
    role: 'Developer',
    status: 'Active',
    department: 'IT',
    joinDate: '2023-03-10',
    salary: 65000,
  },
  {
    id: '4',
    name: 'Fatma Şahin',
    email: 'fatma.sahin@example.com',
    role: 'User',
    status: 'Pending',
    department: 'HR',
    joinDate: '2024-01-05',
    salary: 55000,
  },
  {
    id: '5',
    name: 'Ali Çelik',
    email: 'ali.celik@example.com',
    role: 'Developer',
    status: 'Active',
    department: 'IT',
    joinDate: '2022-09-12',
    salary: 70000,
  },
  {
    id: '6',
    name: 'Zeynep Arslan',
    email: 'zeynep.arslan@example.com',
    role: 'Manager',
    status: 'Active',
    department: 'Marketing',
    joinDate: '2021-11-08',
    salary: 78000,
  },
  {
    id: '7',
    name: 'Mustafa Yıldız',
    email: 'mustafa.yildiz@example.com',
    role: 'User',
    status: 'Inactive',
    department: 'Sales',
    joinDate: '2020-05-18',
    salary: 52000,
  },
  {
    id: '8',
    name: 'Elif Özkan',
    email: 'elif.ozkan@example.com',
    role: 'Developer',
    status: 'Active',
    department: 'IT',
    joinDate: '2023-07-22',
    salary: 68000,
  },
  {
    id: '9',
    name: 'Hasan Aydın',
    email: 'hasan.aydin@example.com',
    role: 'Admin',
    status: 'Active',
    department: 'IT',
    joinDate: '2020-02-14',
    salary: 90000,
  },
  {
    id: '10',
    name: 'Selin Koç',
    email: 'selin.koc@example.com',
    role: 'Manager',
    status: 'Active',
    department: 'HR',
    joinDate: '2022-04-30',
    salary: 72000,
  },
  {
    id: '11',
    name: 'Emre Yurt',
    email: 'emre.yurt@example.com',
    role: 'User',
    status: 'Pending',
    department: 'Sales',
    joinDate: '2024-02-01',
    salary: 48000,
  },
  {
    id: '12',
    name: 'Deniz Öztürk',
    email: 'deniz.ozturk@example.com',
    role: 'Developer',
    status: 'Active',
    department: 'IT',
    joinDate: '2023-08-15',
    salary: 67000,
  },
  {
    id: '13',
    name: 'Cansu Güneş',
    email: 'cansu.gunes@example.com',
    role: 'User',
    status: 'Active',
    department: 'Marketing',
    joinDate: '2022-10-05',
    salary: 54000,
  },
  {
    id: '14',
    name: 'Burak Acar',
    email: 'burak.acar@example.com',
    role: 'Developer',
    status: 'Active',
    department: 'IT',
    joinDate: '2021-12-20',
    salary: 73000,
  },
  {
    id: '15',
    name: 'Merve Aksoy',
    email: 'merve.aksoy@example.com',
    role: 'Manager',
    status: 'Active',
    department: 'Sales',
    joinDate: '2020-08-25',
    salary: 76000,
  },
  {
    id: '16',
    name: 'Kerem Polat',
    email: 'kerem.polat@example.com',
    role: 'User',
    status: 'Inactive',
    department: 'HR',
    joinDate: '2019-03-12',
    salary: 50000,
  },
  {
    id: '17',
    name: 'Ece Karaca',
    email: 'ece.karaca@example.com',
    role: 'Developer',
    status: 'Active',
    department: 'IT',
    joinDate: '2023-05-18',
    salary: 66000,
  },
  {
    id: '18',
    name: 'Onur Taş',
    email: 'onur.tas@example.com',
    role: 'User',
    status: 'Active',
    department: 'Marketing',
    joinDate: '2023-01-09',
    salary: 53000,
  },
  {
    id: '19',
    name: 'Gizem Kurt',
    email: 'gizem.kurt@example.com',
    role: 'Admin',
    status: 'Active',
    department: 'IT',
    joinDate: '2021-07-14',
    salary: 87000,
  },
  {
    id: '20',
    name: 'Barış Çetin',
    email: 'baris.cetin@example.com',
    role: 'Manager',
    status: 'Active',
    department: 'Sales',
    joinDate: '2022-11-22',
    salary: 74000,
  },
]

// Mock Products Data
export const mockProducts: Product[] = [
  {
    id: 'P001',
    name: 'MacBook Pro 16"',
    category: 'Electronics',
    price: 2499.99,
    stock: 45,
    status: 'In Stock',
    rating: 4.8,
    brand: 'Apple',
  },
  {
    id: 'P002',
    name: 'iPhone 15 Pro',
    category: 'Electronics',
    price: 1199.99,
    stock: 120,
    status: 'In Stock',
    rating: 4.9,
    brand: 'Apple',
  },
  {
    id: 'P003',
    name: 'AirPods Pro',
    category: 'Electronics',
    price: 249.99,
    stock: 8,
    status: 'Low Stock',
    rating: 4.7,
    brand: 'Apple',
  },
  {
    id: 'P004',
    name: 'Samsung Galaxy S24',
    category: 'Electronics',
    price: 899.99,
    stock: 0,
    status: 'Out of Stock',
    rating: 4.6,
    brand: 'Samsung',
  },
  {
    id: 'P005',
    name: 'Dell XPS 15',
    category: 'Electronics',
    price: 1799.99,
    stock: 32,
    status: 'In Stock',
    rating: 4.5,
    brand: 'Dell',
  },
  {
    id: 'P006',
    name: 'Sony WH-1000XM5',
    category: 'Electronics',
    price: 399.99,
    stock: 67,
    status: 'In Stock',
    rating: 4.8,
    brand: 'Sony',
  },
  {
    id: 'P007',
    name: 'iPad Air',
    category: 'Electronics',
    price: 599.99,
    stock: 5,
    status: 'Low Stock',
    rating: 4.7,
    brand: 'Apple',
  },
  {
    id: 'P008',
    name: 'Logitech MX Master 3S',
    category: 'Accessories',
    price: 99.99,
    stock: 156,
    status: 'In Stock',
    rating: 4.9,
    brand: 'Logitech',
  },
  {
    id: 'P009',
    name: 'LG UltraWide Monitor',
    category: 'Electronics',
    price: 699.99,
    stock: 28,
    status: 'In Stock',
    rating: 4.6,
    brand: 'LG',
  },
  {
    id: 'P010',
    name: 'Mechanical Keyboard',
    category: 'Accessories',
    price: 149.99,
    stock: 0,
    status: 'Out of Stock',
    rating: 4.5,
    brand: 'Keychron',
  },
]
