// TODO: Remove when API is ready
import type { BranchCargoRecord, BranchDetail, BranchDocument, BranchNote, BranchUser } from "../_types"

const documentBase = "/mock"

function createDocuments(branchId: string, owner: string): BranchDocument[] {
  return [
    {
      id: `${branchId}-doc-1`,
      type: "vergi_levhasi",
      fileName: "vergi_levhasi_2026.pdf",
      fileSize: 245760,
      uploadedAt: "2026-01-12",
      uploadedBy: owner,
      url: `${documentBase}/vergi-levhasi.pdf`,
    },
    {
      id: `${branchId}-doc-2`,
      type: "sozlesme",
      fileName: "acente_sozlesmesi.pdf",
      fileSize: 512000,
      uploadedAt: "2026-01-18",
      uploadedBy: "Genel Merkez Operasyon",
      url: `${documentBase}/sozlesme.pdf`,
    },
  ]
}

function createUsers(branchId: string, manager: string, emailPrefix: string): BranchUser[] {
  const [firstName, lastName] = manager.split(" ")
  return [
    {
      id: `${branchId}-u1`,
      firstName,
      lastName,
      role: "yonetici",
      phone: "0555 100 01 01",
      email: `${emailPrefix}.yonetici@arf.com`,
      status: "active",
      createdAt: "2024-01-15",
      lastActivity: "2026-03-23T09:10:00",
    },
    {
      id: `${branchId}-u2`,
      firstName: "Merve",
      lastName: "Aksoy",
      role: "operator",
      phone: "0555 100 01 02",
      email: `${emailPrefix}.operator@arf.com`,
      status: "active",
      createdAt: "2024-02-01",
      lastActivity: "2026-03-22T17:42:00",
    },
    {
      id: `${branchId}-u3`,
      firstName: "Emre",
      lastName: "Çetin",
      role: "kurye",
      phone: "0555 100 01 03",
      email: `${emailPrefix}.kurye@arf.com`,
      status: branchId === "4" ? "passive" : "active",
      createdAt: "2024-02-11",
      lastActivity: branchId === "4" ? "2026-01-09T12:15:00" : "2026-03-23T08:25:00",
    },
    {
      id: `${branchId}-u4`,
      firstName: "Esra",
      lastName: "Kurt",
      role: "muhasebe",
      phone: "0555 100 01 04",
      email: `${emailPrefix}.muhasebe@arf.com`,
      status: "active",
      createdAt: "2024-03-03",
      lastActivity: "2026-03-21T15:05:00",
    },
  ]
}

function createNotes(branchId: string, branchName: string): BranchNote[] {
  return [
    {
      id: `${branchId}-n1`,
      content: "Dağıtım bölgesinde yeni sokak planı nedeniyle rota güncellemesi yapıldı.",
      category: "operasyon",
      visibility: "public",
      createdBy: `${branchId}-u2`,
      createdByName: "Merve Aksoy",
      createdByRole: "Operatör",
      createdAt: "2026-03-22T13:15:00",
      sourceType: "sube",
      sourceName: branchName,
      branchId,
      branchName,
    },
    {
      id: `${branchId}-n2`,
      content: "Şubat hakediş mutabakatı için banka hesap bilgileri teyit edildi.",
      category: "finans",
      visibility: "internal",
      createdBy: "hq-1",
      createdByName: "Seda Yalın",
      createdByRole: "Genel Merkez Finans",
      createdAt: "2026-03-21T10:40:00",
      sourceType: "genel_merkez",
      sourceName: "Genel Merkez",
      branchId,
      branchName,
    },
  ]
}

export const mockAssignableUsers: BranchUser[] = [
  {
    id: "pool-u1",
    firstName: "Hakan",
    lastName: "Bulut",
    role: "operator",
    phone: "0555 700 10 10",
    email: "hakan.bulut@arf.com",
    status: "active",
    createdAt: "2025-11-10",
    lastActivity: "2026-03-23T07:55:00",
  },
  {
    id: "pool-u2",
    firstName: "Gizem",
    lastName: "Duru",
    role: "kurye",
    phone: "0555 700 20 20",
    email: "gizem.duru@arf.com",
    status: "active",
    createdAt: "2025-12-12",
    lastActivity: "2026-03-22T18:20:00",
  },
  {
    id: "pool-u3",
    firstName: "Onur",
    lastName: "Taş",
    role: "muhasebe",
    phone: "0555 700 30 30",
    email: "onur.tas@arf.com",
    status: "active",
    createdAt: "2025-10-05",
    lastActivity: "2026-03-20T09:30:00",
  },
]

export const mockBranchDetails: BranchDetail[] = [
  {
    id: "1",
    kod: "IST-001",
    ad: "İstanbul Merkez",
    il: "İstanbul",
    ilce: "Kadıköy",
    mahalle: "Moda Mah.",
    acikAdres: "Moda Cad. No:12 Daire:3",
    telefon: "0216 123 45 67",
    eposta: "ist.merkez@arf.com",
    calismaSaatleri: "Pzt-Cmt 08:00-18:00",
    vergiDairesi: "Kadıköy VD",
    vkn: "1234567890",
    acenteSahibi: "Ali Yılmaz",
    acenteSahibiTelefon: "0532 111 22 33",
    acenteSahibiEposta: "ali.yilmaz@arfpartner.com",
    acenteYoneticisi: "Derya Aydın",
    acenteYoneticisiTelefon: "0532 444 66 77",
    managerUserId: "1-u1",
    alimHakedisOrani: 0.2,
    dagitimHakedisOrani: 0.25,
    bankAdi: "Ziraat Bankası",
    iban: "TR33 0001 0017 4579 2316 1100 01",
    hesapSahibi: "Ali Yılmaz",
    latitude: 40.9876,
    longitude: 29.0332,
    status: "active",
    createdAt: "2024-01-15",
    bagliMerkezId: "tc-001",
    bagliMerkezAdi: "İstanbul Anadolu Transfer Merkezi",
    bagliMerkezKodu: "TC-IST-A",
    bagliMerkezSehir: "İstanbul",
    documents: createDocuments("1", "Ali Yılmaz"),
    users: createUsers("1", "Ali Yılmaz", "istanbul.merkez"),
    notes: createNotes("1", "İstanbul Merkez Şubesi"),
    commissionRecords: [
      {
        id: "1-c1",
        processDate: "2026-03-10T09:30:00",
        trackingNo: "ARF-1001",
        transactionType: "alim",
        kargoBedeli: 1000,
        oran: 0.2,
        hesaplamaDetayi: "1.000 TL x %20",
        netKazanc: 200,
        status: "confirmed",
      },
      {
        id: "1-c2",
        processDate: "2026-03-10T18:10:00",
        trackingNo: "ARF-1001",
        transactionType: "dagitim",
        kargoBedeli: 1000,
        oran: 0.25,
        hesaplamaDetayi: "1.000 TL x %25",
        netKazanc: 250,
        status: "confirmed",
      },
      {
        id: "1-c3",
        processDate: "2026-03-18T12:10:00",
        trackingNo: "ARF-1024",
        transactionType: "dagitim",
        kargoBedeli: 640,
        oran: 0.25,
        hesaplamaDetayi: "640 TL x %25",
        netKazanc: 160,
        status: "pending",
      },
      {
        id: "1-c4",
        processDate: "2026-03-20T08:15:00",
        trackingNo: "ARF-1038",
        transactionType: "dagitim",
        kargoBedeli: 390,
        oran: 0.25,
        hesaplamaDetayi: "390 TL x %25",
        netKazanc: 0,
        status: "cancelled",
      },
    ],
  },
  {
    id: "2",
    kod: "ANK-001",
    ad: "Ankara Merkez",
    il: "Ankara",
    ilce: "Çankaya",
    mahalle: "Kavaklıdere",
    acikAdres: "Tunus Cad. No:28",
    telefon: "0312 234 56 78",
    eposta: "ank.merkez@arf.com",
    calismaSaatleri: "Pzt-Cmt 08:30-18:30",
    vergiDairesi: "Çankaya VD",
    vkn: "2345678901",
    acenteSahibi: "Veli Demir",
    acenteSahibiTelefon: "0533 234 56 78",
    acenteSahibiEposta: "veli.demir@arfpartner.com",
    managerUserId: "2-u1",
    alimHakedisOrani: 0.18,
    dagitimHakedisOrani: 0.24,
    bankAdi: "İş Bankası",
    iban: "TR12 0006 4000 0011 2345 6789 01",
    hesapSahibi: "Veli Demir",
    latitude: 39.9076,
    longitude: 32.8636,
    status: "active",
    createdAt: "2024-02-01",
    bagliMerkezId: "tc-002",
    bagliMerkezAdi: "Ankara Transfer Merkezi",
    bagliMerkezKodu: "TC-ANK",
    bagliMerkezSehir: "Ankara",
    documents: createDocuments("2", "Veli Demir"),
    users: createUsers("2", "Veli Demir", "ankara.merkez"),
    notes: createNotes("2", "Ankara Merkez Şubesi"),
    commissionRecords: [
      {
        id: "2-c1",
        processDate: "2026-03-13T10:20:00",
        trackingNo: "ARF-2008",
        transactionType: "alim",
        kargoBedeli: 750,
        oran: 0.18,
        hesaplamaDetayi: "750 TL x %18",
        netKazanc: 135,
        status: "confirmed",
      },
      {
        id: "2-c2",
        processDate: "2026-03-17T16:40:00",
        trackingNo: "ARF-2015",
        transactionType: "dagitim",
        kargoBedeli: 920,
        oran: 0.24,
        hesaplamaDetayi: "920 TL x %24",
        netKazanc: 220.8,
        status: "pending",
      },
    ],
  },
  {
    id: "3",
    kod: "IZM-001",
    ad: "İzmir Merkez",
    il: "İzmir",
    ilce: "Konak",
    mahalle: "Alsancak",
    acikAdres: "Kıbrıs Şehitleri Cad. No:91",
    telefon: "0232 345 67 89",
    eposta: "izm.merkez@arf.com",
    calismaSaatleri: "Pzt-Cmt 08:00-18:00",
    vergiDairesi: "Konak VD",
    vkn: "3456789012",
    acenteSahibi: "Ayşe Kaya",
    acenteSahibiTelefon: "0534 345 67 89",
    acenteSahibiEposta: "ayse.kaya@arfpartner.com",
    managerUserId: "3-u1",
    alimHakedisOrani: 0.19,
    dagitimHakedisOrani: 0.24,
    bankAdi: "Garanti BBVA",
    iban: "TR21 0062 1000 0456 1234 5678 90",
    hesapSahibi: "Ayşe Kaya",
    latitude: 38.4237,
    longitude: 27.1428,
    status: "active",
    createdAt: "2024-02-12",
    bagliMerkezId: "tc-003",
    bagliMerkezAdi: "İzmir Transfer Merkezi",
    bagliMerkezKodu: "TC-IZM",
    bagliMerkezSehir: "İzmir",
    documents: createDocuments("3", "Ayşe Kaya"),
    users: createUsers("3", "Ayşe Kaya", "izmir.merkez"),
    notes: createNotes("3", "İzmir Merkez Şubesi"),
    commissionRecords: [
      {
        id: "3-c1",
        processDate: "2026-03-11T11:50:00",
        trackingNo: "ARF-3003",
        transactionType: "alim",
        kargoBedeli: 460,
        oran: 0.19,
        hesaplamaDetayi: "460 TL x %19",
        netKazanc: 87.4,
        status: "confirmed",
      },
    ],
  },
  {
    id: "4",
    kod: "IST-002",
    ad: "İstanbul Anadolu",
    il: "İstanbul",
    ilce: "Üsküdar",
    mahalle: "Altunizade",
    acikAdres: "Kısıklı Cad. No:44",
    telefon: "0216 456 78 90",
    eposta: "ist.anadolu@arf.com",
    calismaSaatleri: "Pzt-Cmt 09:00-17:30",
    vergiDairesi: "Üsküdar VD",
    vkn: "4567890123",
    acenteSahibi: "Mehmet Can",
    acenteSahibiTelefon: "0535 456 78 90",
    acenteSahibiEposta: "mehmet.can@arfpartner.com",
    managerUserId: "4-u1",
    alimHakedisOrani: 0.2,
    dagitimHakedisOrani: 0.22,
    bankAdi: "Akbank",
    iban: "TR64 0046 2000 1123 4567 8901 23",
    hesapSahibi: "Mehmet Can",
    latitude: 41.0214,
    longitude: 29.0536,
    status: "passive",
    createdAt: "2024-03-01",
    bagliMerkezId: "tc-001",
    bagliMerkezAdi: "İstanbul Anadolu Transfer Merkezi",
    bagliMerkezKodu: "TC-IST-A",
    bagliMerkezSehir: "İstanbul",
    documents: createDocuments("4", "Mehmet Can"),
    users: createUsers("4", "Mehmet Can", "istanbul.anadolu"),
    notes: createNotes("4", "İstanbul Anadolu Şubesi"),
    commissionRecords: [
      {
        id: "4-c1",
        processDate: "2026-03-08T14:10:00",
        trackingNo: "ARF-4010",
        transactionType: "dagitim",
        kargoBedeli: 510,
        oran: 0.22,
        hesaplamaDetayi: "510 TL x %22",
        netKazanc: 112.2,
        status: "cancelled",
      },
    ],
  },
]

export const mockBranchCargoes: BranchCargoRecord[] = [
  {
    id: "cg-1",
    takipNo: "ARF-1001",
    yon: "gonderici",
    gondericiSubeId: "1",
    gondericiSubeAdi: "İstanbul Merkez",
    aliciSubeId: "1",
    aliciSubeAdi: "İstanbul Merkez",
    gondericiAdSoyad: "Aslı Kılıç",
    aliciAdSoyad: "Okan Er",
    aliciTelefon: "0532 111 11 11",
    odemeTuru: "Gönderici Ödemeli",
    faturaTuru: "Gönderici",
    matrah: 833.33,
    kdv: 166.67,
    toplam: 1000,
    tAdet: 2,
    tDesi: 10,
    parcaListesi: "2 parça",
    irsaliyeNo: "IRS-10011",
    atfNo: "",
    durum: "teslim_edildi",
    faturaDurumu: "kesildi",
    tahsilatDurumu: "tahsil_edildi",
    olusturan: "Ali Yılmaz",
    tarih: "2026-03-10T09:30:00",
    sonIslemZamani: "2026-03-10T18:10:00",
    teslimTarihi: "2026-03-10T18:10:00",
  },
  {
    id: "cg-2",
    takipNo: "ARF-1024",
    yon: "alici",
    gondericiSubeId: "2",
    gondericiSubeAdi: "Ankara Merkez",
    aliciSubeId: "1",
    aliciSubeAdi: "İstanbul Merkez",
    gondericiAdSoyad: "Nazlı Koç",
    aliciAdSoyad: "Mert Tan",
    aliciTelefon: "0533 222 22 22",
    odemeTuru: "Alıcı Ödemeli",
    faturaTuru: "Alıcı",
    matrah: 533.33,
    kdv: 106.67,
    toplam: 640,
    tAdet: 1,
    tDesi: 5,
    parcaListesi: "1 parça",
    irsaliyeNo: "IRS-10241",
    atfNo: "",
    durum: "olusturuldu",
    faturaDurumu: "kesilmedi",
    tahsilatDurumu: "beklemede",
    olusturan: "Merve Aksoy",
    tarih: "2026-03-18T12:10:00",
    sonIslemZamani: "2026-03-18T12:10:00",
  },
  {
    id: "cg-3",
    takipNo: "ARF-1038",
    yon: "alici",
    gondericiSubeId: "3",
    gondericiSubeAdi: "İzmir Merkez",
    aliciSubeId: "1",
    aliciSubeAdi: "İstanbul Merkez",
    gondericiAdSoyad: "Bora Topal",
    aliciAdSoyad: "Sibel Öztürk",
    aliciTelefon: "0534 333 33 33",
    odemeTuru: "Gönderici Ödemeli",
    faturaTuru: "Gönderici",
    matrah: 325,
    kdv: 65,
    toplam: 390,
    tAdet: 1,
    tDesi: 7,
    parcaListesi: "1 parça",
    irsaliyeNo: "IRS-10381",
    atfNo: "",
    durum: "iade",
    faturaDurumu: "kesilmedi",
    tahsilatDurumu: "iptal",
    olusturan: "Bora Topal",
    tarih: "2026-03-20T08:15:00",
    sonIslemZamani: "2026-03-20T08:15:00",
  },
  {
    id: "cg-4",
    takipNo: "ARF-2008",
    yon: "gonderici",
    gondericiSubeId: "2",
    gondericiSubeAdi: "Ankara Merkez",
    aliciSubeId: "3",
    aliciSubeAdi: "İzmir Merkez",
    gondericiAdSoyad: "Arda Güner",
    aliciAdSoyad: "Hande Acar",
    aliciTelefon: "0535 444 44 44",
    odemeTuru: "Gönderici Ödemeli",
    faturaTuru: "Gönderici",
    matrah: 625,
    kdv: 125,
    toplam: 750,
    tAdet: 3,
    tDesi: 15,
    parcaListesi: "3 parça",
    irsaliyeNo: "IRS-20081",
    atfNo: "ATF-2008A",
    durum: "teslim_edildi",
    faturaDurumu: "kesildi",
    tahsilatDurumu: "tahsil_edildi",
    olusturan: "Veli Demir",
    tarih: "2026-03-13T10:20:00",
    sonIslemZamani: "2026-03-14T15:20:00",
    teslimTarihi: "2026-03-14T15:20:00",
  },
  {
    id: "cg-5",
    takipNo: "ARF-2015",
    yon: "alici",
    gondericiSubeId: "4",
    gondericiSubeAdi: "İstanbul Anadolu",
    aliciSubeId: "2",
    aliciSubeAdi: "Ankara Merkez",
    gondericiAdSoyad: "Funda Özen",
    aliciAdSoyad: "Levent Işık",
    aliciTelefon: "0536 555 55 55",
    odemeTuru: "Alıcı Ödemeli",
    faturaTuru: "Alıcı",
    matrah: 766.67,
    kdv: 153.33,
    toplam: 920,
    tAdet: 2,
    tDesi: 12,
    parcaListesi: "2 parça",
    irsaliyeNo: "IRS-20151",
    atfNo: "",
    durum: "dagitimda",
    faturaDurumu: "kesilmedi",
    tahsilatDurumu: "beklemede",
    olusturan: "Gizem Duru",
    tarih: "2026-03-17T16:40:00",
    sonIslemZamani: "2026-03-18T08:00:00",
    varisTarihi: "2026-03-18T07:50:00",
  },
  {
    id: "cg-6",
    takipNo: "ARF-3003",
    yon: "gonderici",
    gondericiSubeId: "3",
    gondericiSubeAdi: "İzmir Merkez",
    aliciSubeId: "2",
    aliciSubeAdi: "Ankara Merkez",
    gondericiAdSoyad: "Melis Ersoy",
    aliciAdSoyad: "Tolga Aras",
    aliciTelefon: "0537 666 66 66",
    odemeTuru: "Gönderici Ödemeli",
    faturaTuru: "Gönderici",
    matrah: 383.33,
    kdv: 76.67,
    toplam: 460,
    tAdet: 1,
    tDesi: 8,
    parcaListesi: "1 parça",
    irsaliyeNo: "IRS-30031",
    atfNo: "",
    durum: "teslim_edildi",
    faturaDurumu: "kesildi",
    tahsilatDurumu: "tahsil_edildi",
    olusturan: "Ayşe Kaya",
    tarih: "2026-03-11T11:50:00",
    sonIslemZamani: "2026-03-12T09:20:00",
    teslimTarihi: "2026-03-12T09:20:00",
  },
  {
    id: "cg-7",
    takipNo: "ARF-4010",
    yon: "gonderici",
    gondericiSubeId: "4",
    gondericiSubeAdi: "İstanbul Anadolu",
    aliciSubeId: "1",
    aliciSubeAdi: "İstanbul Merkez",
    gondericiAdSoyad: "Ömer Kara",
    aliciAdSoyad: "Ece Uslu",
    aliciTelefon: "0538 777 77 77",
    odemeTuru: "Gönderici Ödemeli",
    faturaTuru: "Gönderici",
    matrah: 425,
    kdv: 85,
    toplam: 510,
    tAdet: 1,
    tDesi: 6,
    parcaListesi: "1 parça",
    irsaliyeNo: "IRS-40101",
    atfNo: "",
    durum: "iptal_edildi",
    faturaDurumu: "kesilmedi",
    tahsilatDurumu: "iptal",
    olusturan: "Mehmet Can",
    tarih: "2026-03-08T14:10:00",
    sonIslemZamani: "2026-03-08T14:10:00",
  },
  {
    id: "cg-8",
    takipNo: "ARF-4015",
    yon: "alici",
    gondericiSubeId: "1",
    gondericiSubeAdi: "İstanbul Merkez",
    aliciSubeId: "4",
    aliciSubeAdi: "İstanbul Anadolu",
    gondericiAdSoyad: "Büşra Işın",
    aliciAdSoyad: "Kerem Usta",
    aliciTelefon: "0539 888 88 88",
    odemeTuru: "Alıcı Ödemeli",
    faturaTuru: "Alıcı",
    matrah: 704.17,
    kdv: 140.83,
    toplam: 845,
    tAdet: 2,
    tDesi: 14,
    parcaListesi: "2 parça",
    irsaliyeNo: "IRS-40151",
    atfNo: "ATF-4015B",
    durum: "olusturuldu",
    faturaDurumu: "kesilmedi",
    tahsilatDurumu: "beklemede",
    olusturan: "Ali Yılmaz",
    tarih: "2026-03-19T13:40:00",
    sonIslemZamani: "2026-03-19T13:40:00",
  },
]

export function getBranchDetailById(id: string): BranchDetail | undefined {
  return mockBranchDetails.find((branch) => branch.id === id)
}
