import type {
  LastmileUser,
  UserAccessStatus,
  UserListKpi,
  UserStatusScope,
} from '../_types/user'

export const USERS_MOCK: LastmileUser[] = [
  {
    id: 'u-001',
    ad_soyad: 'Ayşe Demir',
    email: 'ayse@getarf.com',
    telefon: '+90 532 999 8877',
    profil_url: null,
    kullanici_tipi: 'ic_ekip',
    bagli_kurum: 'Merkez Operasyon',
    musteri_id: null,
    rol: 'super_admin',
    durum: 'aktif',
    son_giris: '2026-07-17T09:15:00',
    olusturma_tarihi: '2025-11-02T10:20:00',
    olusturan: 'Sistem',
    personel: {
      tckn: '12345678901',
      dogum_tarihi: '1990-04-12',
      cinsiyet: 'kadin',
      medeni_hal: 'evli',
      kan_grubu: 'A Rh+',
      ikamet_adresi: 'Atatürk Mah. Cumhuriyet Cad. No:18/4 Kadıköy / İstanbul',
      ise_giris_tarihi: '2022-03-01',
      unvan: 'Operasyon Direktörü',
      acil_kisi: 'Mehmet Demir',
      acil_telefon: '+90 532 111 2233',
      egitim_durumu: 'Lisans',
    },
    evraklar: [
      {
        id: 'doc-u-001-kimlik',
        name: 'nufus-cuzdani.pdf',
        size: 312_000,
        mimeType: 'application/pdf',
        type: 'kimlik',
        uploadedAt: '2025-11-02T10:25:00.000Z',
        uploadedBy: 'İnsan Kaynakları',
      },
      {
        id: 'doc-u-001-sozlesme',
        name: 'is-sozlesmesi.pdf',
        size: 540_120,
        mimeType: 'application/pdf',
        type: 'sozlesme',
        uploadedAt: '2025-11-02T10:28:00.000Z',
        uploadedBy: 'İnsan Kaynakları',
      },
      {
        id: 'doc-u-001-ikamet',
        name: 'ikametgah.pdf',
        size: 198_400,
        mimeType: 'application/pdf',
        type: 'ikametgah',
        uploadedAt: '2025-11-03T09:10:00.000Z',
        uploadedBy: 'Ayşe Demir',
      },
    ],
  },
  {
    id: 'u-002',
    ad_soyad: 'Mehmet Kaya',
    email: 'mehmet.kaya@getarf.com',
    telefon: '+90 533 111 2233',
    profil_url: null,
    kullanici_tipi: 'ic_ekip',
    bagli_kurum: 'Merkez Operasyon',
    musteri_id: null,
    rol: 'bolge_planlamacisi',
    durum: 'aktif',
    son_giris: '2026-07-29T14:42:00',
    olusturma_tarihi: '2025-12-18T11:05:00',
    olusturan: 'Ayşe Demir',
    personel: {
      tckn: '23456789012',
      dogum_tarihi: '1988-09-21',
      cinsiyet: 'erkek',
      medeni_hal: 'bekar',
      kan_grubu: '0 Rh+',
      ikamet_adresi: 'Bahçelievler Mah. 7. Cad. No:5 Çankaya / Ankara',
      ise_giris_tarihi: '2023-01-16',
      unvan: 'Bölge Planlamacısı',
      acil_kisi: 'Ayşe Kaya',
      acil_telefon: '+90 533 444 5566',
      egitim_durumu: 'Yüksek Lisans',
    },
    evraklar: [
      {
        id: 'doc-u-002-kimlik',
        name: 'kimlik.pdf',
        size: 280_000,
        mimeType: 'application/pdf',
        type: 'kimlik',
        uploadedAt: '2025-12-18T11:20:00.000Z',
        uploadedBy: 'İnsan Kaynakları',
      },
      {
        id: 'doc-u-002-sgk',
        name: 'sgk-giris.pdf',
        size: 156_000,
        mimeType: 'application/pdf',
        type: 'sgk',
        uploadedAt: '2025-12-18T11:22:00.000Z',
        uploadedBy: 'İnsan Kaynakları',
      },
    ],
  },
  {
    id: 'u-003',
    ad_soyad: 'Zeynep Arslan',
    email: 'zeynep.arslan@getarf.com',
    telefon: '+90 534 444 5566',
    profil_url: null,
    kullanici_tipi: 'ic_ekip',
    bagli_kurum: 'İstanbul Bölge Ofisi',
    musteri_id: null,
    rol: 'operasyon_yoneticisi',
    durum: 'aktif',
    son_giris: '2026-07-30T08:05:00',
    olusturma_tarihi: '2026-01-09T09:40:00',
    olusturan: 'Ayşe Demir',
    personel: {
      tckn: null,
      dogum_tarihi: null,
      cinsiyet: null,
      medeni_hal: null,
      kan_grubu: null,
      ikamet_adresi: null,
      ise_giris_tarihi: null,
      unvan: null,
      acil_kisi: null,
      acil_telefon: null,
      egitim_durumu: null,
    },
    evraklar: [],
  },
  {
    id: 'u-004',
    ad_soyad: 'Can Öztürk',
    email: 'can.ozturk@getarf.com',
    telefon: '+90 535 777 8899',
    profil_url: null,
    kullanici_tipi: 'ic_ekip',
    bagli_kurum: 'Merkez Operasyon',
    musteri_id: null,
    rol: 'sadece_izleyici',
    durum: 'pasif',
    son_giris: '2026-05-12T11:20:00',
    olusturma_tarihi: '2026-02-14T15:10:00',
    olusturan: 'Mehmet Kaya',
    personel: {
      tckn: null,
      dogum_tarihi: null,
      cinsiyet: null,
      medeni_hal: null,
      kan_grubu: null,
      ikamet_adresi: null,
      ise_giris_tarihi: null,
      unvan: null,
      acil_kisi: null,
      acil_telefon: null,
      egitim_durumu: null,
    },
    evraklar: [],
  },
  {
    id: 'u-005',
    ad_soyad: 'Elif Yıldız',
    email: 'elif.yildiz@getarf.com',
    telefon: '+90 536 222 3344',
    profil_url: null,
    kullanici_tipi: 'ic_ekip',
    bagli_kurum: 'Ankara Bölge Ofisi',
    musteri_id: null,
    rol: 'bolge_planlamacisi',
    durum: 'davet',
    son_giris: null,
    olusturma_tarihi: '2026-07-28T13:25:00',
    olusturan: 'Zeynep Arslan',
    personel: {
      tckn: null,
      dogum_tarihi: null,
      cinsiyet: null,
      medeni_hal: null,
      kan_grubu: null,
      ikamet_adresi: null,
      ise_giris_tarihi: null,
      unvan: null,
      acil_kisi: null,
      acil_telefon: null,
      egitim_durumu: null,
    },
    evraklar: [],
  },
  {
    id: 'u-006',
    ad_soyad: 'Burak Şahin',
    email: 'burak.sahin@abceticaret.com',
    telefon: '+90 537 555 6677',
    profil_url: null,
    kullanici_tipi: 'musteri',
    bagli_kurum: 'ABC E-Ticaret A.Ş.',
    musteri_id: 'cust-001',
    rol: 'musteri_depo_yoneticisi',
    durum: 'aktif',
    son_giris: '2026-07-29T16:30:00',
    olusturma_tarihi: '2026-03-01T10:00:00',
    olusturan: 'Ayşe Demir',
    personel: {
      tckn: '34567890123',
      dogum_tarihi: '1992-11-03',
      cinsiyet: 'erkek',
      medeni_hal: 'evli',
      kan_grubu: 'B Rh+',
      ikamet_adresi: 'Yenibosna Mah. Lojistik Cad. No:22 Bahçelievler / İstanbul',
      ise_giris_tarihi: '2026-03-01',
      unvan: 'Depo Yöneticisi',
      acil_kisi: 'Elif Şahin',
      acil_telefon: '+90 537 222 3344',
      egitim_durumu: 'Lisans',
    },
    evraklar: [
      {
        id: 'doc-u-006-kimlik',
        name: 'kimlik-fotokopi.pdf',
        size: 220_000,
        mimeType: 'application/pdf',
        type: 'kimlik',
        uploadedAt: '2026-03-01T10:10:00.000Z',
        uploadedBy: 'Ayşe Demir',
      },
    ],
  },
  {
    id: 'u-007',
    ad_soyad: 'Selin Aksoy',
    email: 'selin.aksoy@abceticaret.com',
    telefon: '+90 538 888 9900',
    profil_url: null,
    kullanici_tipi: 'musteri',
    bagli_kurum: 'ABC E-Ticaret A.Ş.',
    musteri_id: 'cust-001',
    rol: 'musteri_izleyici',
    durum: 'aktif',
    son_giris: '2026-07-22T10:10:00',
    olusturma_tarihi: '2026-03-15T14:35:00',
    olusturan: 'Burak Şahin',
    personel: {
      tckn: null,
      dogum_tarihi: null,
      cinsiyet: null,
      medeni_hal: null,
      kan_grubu: null,
      ikamet_adresi: null,
      ise_giris_tarihi: null,
      unvan: null,
      acil_kisi: null,
      acil_telefon: null,
      egitim_durumu: null,
    },
    evraklar: [],
  },
  {
    id: 'u-008',
    ad_soyad: 'Hakan Çelik',
    email: 'hakan.celik@nordlojistik.com',
    telefon: '+90 539 123 4567',
    profil_url: null,
    kullanici_tipi: 'musteri',
    bagli_kurum: 'Nord Lojistik Ltd.',
    musteri_id: 'cust-002',
    rol: 'musteri_depo_yoneticisi',
    durum: 'aktif',
    son_giris: '2026-07-18T13:45:00',
    olusturma_tarihi: '2026-04-02T11:15:00',
    olusturan: 'Mehmet Kaya',
    personel: {
      tckn: null,
      dogum_tarihi: null,
      cinsiyet: null,
      medeni_hal: null,
      kan_grubu: null,
      ikamet_adresi: null,
      ise_giris_tarihi: null,
      unvan: null,
      acil_kisi: null,
      acil_telefon: null,
      egitim_durumu: null,
    },
    evraklar: [],
  },
  {
    id: 'u-009',
    ad_soyad: 'Deniz Acar',
    email: 'deniz.acar@nordlojistik.com',
    telefon: '+90 541 234 5678',
    profil_url: null,
    kullanici_tipi: 'musteri',
    bagli_kurum: 'Nord Lojistik Ltd.',
    musteri_id: 'cust-002',
    rol: 'sadece_izleyici',
    durum: 'davet',
    son_giris: null,
    olusturma_tarihi: '2026-07-25T16:50:00',
    olusturan: 'Hakan Çelik',
    personel: {
      tckn: null,
      dogum_tarihi: null,
      cinsiyet: null,
      medeni_hal: null,
      kan_grubu: null,
      ikamet_adresi: null,
      ise_giris_tarihi: null,
      unvan: null,
      acil_kisi: null,
      acil_telefon: null,
      egitim_durumu: null,
    },
    evraklar: [],
  },
  {
    id: 'u-010',
    ad_soyad: 'Gülşen Kara',
    email: 'gulsen.kara@hizlimarket.com',
    telefon: '+90 542 345 6789',
    profil_url: null,
    kullanici_tipi: 'musteri',
    bagli_kurum: 'Hızlı Market A.Ş.',
    musteri_id: 'cust-003',
    rol: 'musteri_depo_yoneticisi',
    durum: 'pasif',
    son_giris: '2026-04-03T09:00:00',
    olusturma_tarihi: '2026-01-20T08:30:00',
    olusturan: 'Zeynep Arslan',
    personel: {
      tckn: null,
      dogum_tarihi: null,
      cinsiyet: null,
      medeni_hal: null,
      kan_grubu: null,
      ikamet_adresi: null,
      ise_giris_tarihi: null,
      unvan: null,
      acil_kisi: null,
      acil_telefon: null,
      egitim_durumu: null,
    },
    evraklar: [],
  },
  {
    id: 'u-011',
    ad_soyad: 'Onur Polat',
    email: 'onur.polat@getarf.com',
    telefon: '+90 543 456 7890',
    profil_url: null,
    kullanici_tipi: 'ic_ekip',
    bagli_kurum: 'Merkez Operasyon',
    musteri_id: null,
    rol: 'operasyon_yoneticisi',
    durum: 'aktif',
    son_giris: '2026-07-30T07:50:00',
    olusturma_tarihi: '2025-10-11T12:00:00',
    olusturan: 'Ayşe Demir',
    personel: {
      tckn: null,
      dogum_tarihi: null,
      cinsiyet: null,
      medeni_hal: null,
      kan_grubu: null,
      ikamet_adresi: null,
      ise_giris_tarihi: null,
      unvan: null,
      acil_kisi: null,
      acil_telefon: null,
      egitim_durumu: null,
    },
    evraklar: [],
  },
  {
    id: 'u-012',
    ad_soyad: 'İrem Taş',
    email: 'irem.tas@hizlimarket.com',
    telefon: '+90 544 567 8901',
    profil_url: null,
    kullanici_tipi: 'musteri',
    bagli_kurum: 'Hızlı Market A.Ş.',
    musteri_id: 'cust-003',
    rol: 'musteri_izleyici',
    durum: 'aktif',
    son_giris: '2026-07-27T18:22:00',
    olusturma_tarihi: '2026-05-08T17:05:00',
    olusturan: 'Gülşen Kara',
    personel: {
      tckn: null,
      dogum_tarihi: null,
      cinsiyet: null,
      medeni_hal: null,
      kan_grubu: null,
      ikamet_adresi: null,
      ise_giris_tarihi: null,
      unvan: null,
      acil_kisi: null,
      acil_telefon: null,
      egitim_durumu: null,
    },
    evraklar: [],
  },
]

export function computeUserKpi(items: LastmileUser[]): UserListKpi {
  return {
    total: items.length,
    active: items.filter((item) => item.durum === 'aktif').length,
    suspended: items.filter((item) => item.durum === 'pasif').length,
    invited: items.filter((item) => item.durum === 'davet').length,
    internal: items.filter((item) => item.kullanici_tipi === 'ic_ekip').length,
    customer: items.filter((item) => item.kullanici_tipi === 'musteri').length,
  }
}

export function computeUserStatusCounts(
  items: LastmileUser[]
): Record<UserStatusScope, number> {
  const counts: Record<UserAccessStatus, number> = {
    aktif: 0,
    pasif: 0,
    davet: 0,
    askida: 0,
  }
  for (const item of items) {
    counts[item.durum] += 1
  }
  return {
    all: items.length,
    ...counts,
  }
}
