import type { DriverOption, SupplierOption, TripLineOption, TripRecord, VehicleOption } from "../_types"

export const mockTripLineOptions: TripLineOption[] = [
  {
    id: "line-main-001",
    type: "main",
    name: "Güneydoğu Ana Hat",
    summary: "Silopi Şb. - Cizre Şb. - Nusaybin Şb. - Mardin Şb. - Diyarbakır T.M.",
    stops: ["Silopi Şb.", "Cizre Şb.", "Nusaybin Şb.", "Mardin Şb.", "Diyarbakır T.M."],
  },
  {
    id: "line-hub-001",
    type: "hub",
    name: "Doğu Merkez Hat",
    summary: "Van T.M. - Erciş Şb. - Patnos Şb. - Ağrı Şb.",
    stops: ["Van T.M.", "Erciş Şb.", "Patnos Şb.", "Ağrı Şb."],
  },
  {
    id: "line-feeder-001",
    type: "feeder",
    name: "Mardin Ara Hat",
    summary: "Mardin Şb. - Midyat Şb. - Nusaybin Şb.",
    stops: ["Mardin Şb.", "Midyat Şb.", "Nusaybin Şb."],
  },
]

export const mockSuppliers: SupplierOption[] = [
  { id: "supplier-company", type: "company", name: "Şirket" },
  { id: "supplier-log-001", type: "logistics", name: "AKSA Lojistik" },
  { id: "supplier-log-002", type: "logistics", name: "Merkez Lojistik" },
  { id: "supplier-truck-001", type: "truck_owner", name: "Bedirhan Nakliyat" },
  { id: "supplier-warehouse-001", type: "warehouse", name: "Güney Ambar" },
]

export const mockVehicles: VehicleOption[] = [
  { id: "vehicle-001", supplierId: "supplier-company", plate: "21ABR479" },
  { id: "vehicle-002", supplierId: "supplier-log-001", plate: "34LGT813" },
  { id: "vehicle-003", supplierId: "supplier-log-002", plate: "06MRK248" },
  { id: "vehicle-004", supplierId: "supplier-truck-001", plate: "47BDR001" },
]

export const mockDrivers: DriverOption[] = [
  { id: "driver-001", supplierId: "supplier-company", vehicleId: "vehicle-001", name: "Bedirhan Çalan" },
  { id: "driver-002", supplierId: "supplier-log-001", vehicleId: "vehicle-002", name: "Ahmet Can" },
  { id: "driver-003", supplierId: "supplier-log-002", vehicleId: "vehicle-003", name: "Mahmut Yıldız" },
  { id: "driver-004", supplierId: "supplier-truck-001", vehicleId: "vehicle-004", name: "Ferhat Şahin" },
]

export const mockTrips: TripRecord[] = [
  {
    id: "trip-10000164",
    tripNo: "10000164",
    lineId: "line-main-001",
    lineType: "main",
    lineName: "Güneydoğu Ana Hat",
    lineSummary: "Silopi Şb. - Cizre Şb. - Nusaybin Şb. - Mardin Şb. - Diyarbakır T.M.",
    supplierType: "logistics",
    supplierName: "Merkez Lojistik",
    vehiclePlate: "21ABR479",
    driverName: "Bedirhan Çalan",
    totalPackageCount: 142,
    totalDesi: 4250,
    currentLocationSummary: "Nusaybin Şubesinde (Yükleme Yapılıyor)",
    status: "on_road",
    createdAt: "2026-03-27T11:59:00.000Z",
    updatedAt: "2026-03-27T14:10:00.000Z",
    createdBy: "Ahmet Can",
  },
  {
    id: "trip-10000165",
    tripNo: "10000165",
    lineId: "line-hub-001",
    lineType: "hub",
    lineName: "Doğu Merkez Hat",
    lineSummary: "Van T.M. - Erciş Şb. - Patnos Şb. - Ağrı Şb.",
    supplierType: "company",
    supplierName: "Şirket",
    vehiclePlate: "34LGT813",
    driverName: "Ahmet Can",
    totalPackageCount: 96,
    totalDesi: 3110,
    currentLocationSummary: "Van T.M. çıkış için hazır",
    status: "created",
    createdAt: "2026-03-27T09:12:00.000Z",
    updatedAt: "2026-03-27T09:12:00.000Z",
    createdBy: "Ayşe Demir",
  },
  {
    id: "trip-10000166",
    tripNo: "10000166",
    lineId: "line-feeder-001",
    lineType: "feeder",
    lineName: "Mardin Ara Hat",
    lineSummary: "Mardin Şb. - Midyat Şb. - Nusaybin Şb.",
    supplierType: "warehouse",
    supplierName: "Güney Ambar",
    totalPackageCount: 58,
    totalDesi: 1890,
    currentLocationSummary: "Midyat - Nusaybin arasında (Yolda)",
    status: "on_road",
    createdAt: "2026-03-27T08:05:00.000Z",
    updatedAt: "2026-03-27T12:20:00.000Z",
    createdBy: "Ceyda Kaya",
  },
  {
    id: "trip-10000167",
    tripNo: "10000167",
    lineId: "line-main-001",
    lineType: "main",
    lineName: "Güneydoğu Ana Hat",
    lineSummary: "Silopi Şb. - Cizre Şb. - Nusaybin Şb. - Mardin Şb. - Diyarbakır T.M.",
    supplierType: "truck_owner",
    supplierName: "Bedirhan Nakliyat",
    vehiclePlate: "47BDR001",
    driverName: "Ferhat Şahin",
    totalPackageCount: 130,
    totalDesi: 3975,
    currentLocationSummary: "Sefer başarıyla tamamlandı",
    status: "completed",
    createdAt: "2026-03-26T18:45:00.000Z",
    updatedAt: "2026-03-26T23:10:00.000Z",
    createdBy: "Onur Çetin",
  },
  {
    id: "trip-10000168",
    tripNo: "10000168",
    lineId: "line-hub-001",
    lineType: "hub",
    lineName: "Doğu Merkez Hat",
    lineSummary: "Van T.M. - Erciş Şb. - Patnos Şb. - Ağrı Şb.",
    supplierType: "logistics",
    supplierName: "AKSA Lojistik",
    vehiclePlate: "06MRK248",
    driverName: "Mahmut Yıldız",
    totalPackageCount: 77,
    totalDesi: 2420,
    currentLocationSummary: "Sefer iptal edildi",
    status: "cancelled",
    createdAt: "2026-03-26T16:10:00.000Z",
    updatedAt: "2026-03-26T16:55:00.000Z",
    createdBy: "Ayşe Demir",
  },
]