/* ------------------------------------------------------------------ */
/*  Taşıma Listesi – Mock Veri                                        */
/* ------------------------------------------------------------------ */

import type { TasimaListRow } from "../_types/transport-list"

export const mockTasimalar: TasimaListRow[] = [
  {
    id: "t-1",
    tasimaNo: "TSM-20000001",
    yuklemeTarihi: "2025-01-15 08:00",
    gonderiTipi: "FTL",
    gondericiMusteri: "AHMET KARAN",
    aliciMusteri: "DELTA TİCARET LTD.",
    cikisAdres: "Adana / Seyhan",
    varisAdres: "Kocaeli / Gebze",
    tasimaciFirma: "DELTA TEDARİK",
    aracPlaka: "34 ABC 123",
    surucu: "Ahmet Yılmaz",
    yukTipleri: "Palet",
    toplamAdet: 20,
    toplamAgirlik: 18000,
    toplamHacim: 42.5,
    toplamDesi: 14166,
    alisFiyat: 35000,
    satisFiyat: 42000,
    kar: 7000,
    durum: "teslim_edildi",
    olusturmaTarihi: "2025-01-14 14:30",
    olusturan: "Operasyon Merkezi",
  },
  {
    id: "t-2",
    tasimaNo: "TSM-20000002",
    yuklemeTarihi: "2025-01-18 09:30",
    gonderiTipi: "LTL",
    gondericiMusteri: "YILDIZ GIDA SAN.",
    aliciMusteri: "MEGA DEPOLAMA A.Ş.",
    cikisAdres: "Ankara / Sincan",
    varisAdres: "İzmir / Kemalpaşa",
    tasimaciFirma: "MARS LOJİSTİK",
    aracPlaka: "06 GHI 789",
    surucu: "Ali Kaya",
    yukTipleri: "Koli, IBC",
    toplamAdet: 45,
    toplamAgirlik: 3200,
    toplamHacim: 18.4,
    toplamDesi: 6133,
    alisFiyat: 12000,
    satisFiyat: 15500,
    kar: 3500,
    durum: "yolda",
    olusturmaTarihi: "2025-01-17 10:00",
    olusturan: "Operasyon Merkezi",
  },
  {
    id: "t-3",
    tasimaNo: "TSM-20000003",
    yuklemeTarihi: "2025-01-20 07:00",
    gonderiTipi: "FTL",
    gondericiMusteri: "DELTA TİCARET LTD.",
    aliciMusteri: "AHMET KARAN",
    cikisAdres: "Kocaeli / Gebze",
    varisAdres: "Adana / Seyhan",
    tasimaciFirma: "STAR TAŞIMACILIK",
    aracPlaka: "35 MNO 345",
    surucu: "Emre Koç",
    yukTipleri: "Palet, Bidon",
    toplamAdet: 15,
    toplamAgirlik: 22000,
    toplamHacim: 55.0,
    toplamDesi: 18333,
    alisFiyat: 40000,
    satisFiyat: 48000,
    kar: 8000,
    durum: "yukleniyor",
    olusturmaTarihi: "2025-01-19 16:45",
    olusturan: "Operasyon Merkezi",
  },
]
