// TODO: Remove when API is ready

import type { SupplierRecord } from "../_types"

export const suppliersDb: SupplierRecord[] = [
  {
    id: "1",
    name: "Ekspress24",
    supplierType: "ozmal",
    status: "active",
    contractType: "fixed_salary",
    contactPerson: "Operasyon Müdürü",
    contactPhone: "+905321234567",
    city: "Diyarbakır",
    vehicleCount: 12,
    driverCount: 18,
    activeTripsCount: 5,
    totalTripsCount: 890,
    isDeletable: false,
    isDeactivatable: false,
    hasExpiringDocuments: false,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-03-20T10:00:00.000Z",
    createdBy: "Sistem",
  },
  {
    id: "2",
    name: "Kuzey Lojistik A.Ş.",
    supplierType: "logistics",
    status: "active",
    contractType: "per_trip",
    contactPerson: "Ahmet Demir",
    contactPhone: "+905334567890",
    city: "İstanbul",
    vehicleCount: 4,
    driverCount: 6,
    activeTripsCount: 2,
    totalTripsCount: 145,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: true,
    createdAt: "2025-03-10T09:00:00.000Z",
    updatedAt: "2026-03-25T14:00:00.000Z",
    createdBy: "Mehmet Yıldız",
  },
  {
    id: "3",
    name: "AKSA Lojistik",
    supplierType: "logistics",
    status: "active",
    contractType: "per_desi",
    contactPerson: "Fatma Kaya",
    contactPhone: "+905387654321",
    city: "Ankara",
    vehicleCount: 7,
    driverCount: 10,
    activeTripsCount: 3,
    totalTripsCount: 312,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2024-06-15T08:00:00.000Z",
    updatedAt: "2026-03-22T11:30:00.000Z",
    createdBy: "Ahmet Can",
  },
  {
    id: "4",
    name: "Bedirhan Nakliyat",
    supplierType: "truck_owner",
    status: "active",
    contractType: "per_trip",
    contactPerson: "Bedirhan Şahin",
    contactPhone: "+905412345678",
    city: "Mardin",
    vehicleCount: 2,
    driverCount: 2,
    activeTripsCount: 1,
    totalTripsCount: 78,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2025-01-20T10:00:00.000Z",
    updatedAt: "2026-03-10T16:00:00.000Z",
    createdBy: "Mehmet Yıldız",
  },
  {
    id: "5",
    name: "Çetin Taşımacılık",
    supplierType: "truck_owner",
    status: "active",
    contractType: "per_trip",
    contactPerson: "Hasan Çetin",
    contactPhone: "+905501234567",
    city: "Şanlıurfa",
    vehicleCount: 1,
    driverCount: 1,
    activeTripsCount: 0,
    totalTripsCount: 34,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: true,
    createdAt: "2025-05-05T09:00:00.000Z",
    updatedAt: "2026-02-28T09:00:00.000Z",
    createdBy: "Ahmet Can",
  },
  {
    id: "6",
    name: "Güney Ambar",
    supplierType: "warehouse",
    status: "active",
    contractType: "commission",
    contactPerson: "Ali Yurt",
    contactPhone: "+905609876543",
    city: "Gaziantep",
    vehicleCount: 0,
    driverCount: 0,
    activeTripsCount: 0,
    totalTripsCount: 56,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2025-02-14T08:30:00.000Z",
    updatedAt: "2026-03-01T10:00:00.000Z",
    createdBy: "Mehmet Yıldız",
  },
  {
    id: "7",
    name: "Merkez Lojistik",
    supplierType: "logistics",
    status: "passive",
    contractType: "per_trip",
    contactPerson: "Kadir Arslan",
    contactPhone: "+905323456789",
    city: "Gaziantep",
    vehicleCount: 3,
    driverCount: 4,
    activeTripsCount: 0,
    totalTripsCount: 89,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2024-09-01T07:00:00.000Z",
    updatedAt: "2026-01-15T12:00:00.000Z",
    createdBy: "Ahmet Can",
  },
]

export function computeSupplierKpi(records: SupplierRecord[]) {
  return {
    total: records.length,
    active: records.filter((r) => r.status === "active").length,
    passive: records.filter((r) => r.status === "passive").length,
    ozmal: records.filter((r) => r.supplierType === "ozmal").length,
    logistics: records.filter((r) => r.supplierType === "logistics").length,
    truckOwner: records.filter((r) => r.supplierType === "truck_owner").length,
    warehouse: records.filter((r) => r.supplierType === "warehouse").length,
  }
}
