// TODO: Remove mock when backend API is ready
import type { LastmileCustomer } from '../_types/customer'
import { buildCustomerKpi, countCustomersByStatusScope } from '../_lib/query-customers'

function customer(
  partial: Omit<
    LastmileCustomer,
    | 'bildirim_sms'
    | 'bildirim_email'
    | 'teslimat_kaniti_zorunlu'
    | 'guvenli_teslimat_otp'
  > &
    Partial<
      Pick<
        LastmileCustomer,
        | 'bildirim_sms'
        | 'bildirim_email'
        | 'teslimat_kaniti_zorunlu'
        | 'guvenli_teslimat_otp'
      >
    >
): LastmileCustomer {
  return {
    bildirim_sms: true,
    bildirim_email: true,
    teslimat_kaniti_zorunlu: true,
    guvenli_teslimat_otp: false,
    ...partial,
  }
}

/** Sipariş / finans seed id’leriyle hizalı demo müşteriler */
export const mockCustomerList: LastmileCustomer[] = [
  customer({
    id: 'c-bnf',
    musteri_kodu: 'CUST-1042',
    firma_unvani: 'ABC E-Ticaret A.Ş.',
    marka_kisa_ad: 'ABC E-Ticaret',
    vkn: '1234567890',
    vergi_dairesi: 'Kadıköy',
    durum: 'aktif',
    sektor: 'E-Ticaret',
    entegrasyon_tipi: 'API',
    ana_yetkili: 'Ahmet Yılmaz',
    ana_yetkili_unvan: 'Operasyon Müdürü',
    telefon: '+90 216 555 0101',
    email: 'ops@abceticaret.com',
    fatura_merkez_adresi: 'Caferağa Mh. Moda Cd. No:12, Kadıköy / İstanbul',
    tesis_sayisi: 3,
    merkez_depo_sayisi: 1,
    son_senkronizasyon: '08.08.2026 09:40',
    bugunku_aktif_siparis: 12,
    gunluk_ortalama_hacim: 86,
    toplam_paket: 1240,
    toplam_teslim: 1188,
    toplam_iptal: 22,
    teslimat_basari_orani: 97.2,
    ortalama_gorev_suresi_dk: 18,
    kayit_tarihi: '12.01.2025 11:20',
    il: 'İstanbul',
    ilce: 'Kadıköy',
  }),
  customer({
    id: 'c-modanisa',
    musteri_kodu: 'CUST-1088',
    firma_unvani: 'Modanisa Elektronik Ticaret A.Ş.',
    marka_kisa_ad: 'Modanisa',
    vkn: '9988776655',
    vergi_dairesi: 'Ümraniye',
    durum: 'aktif',
    sektor: 'Perakende',
    entegrasyon_tipi: 'API',
    ana_yetkili: 'Elif Kara',
    ana_yetkili_unvan: 'Lojistik Lideri',
    telefon: '+90 216 444 5566',
    email: 'lojistik@modanisa.com',
    fatura_merkez_adresi: 'Yamanevler Mh. Alemdağ Cd. No:40, Ümraniye / İstanbul',
    tesis_sayisi: 5,
    merkez_depo_sayisi: 2,
    son_senkronizasyon: '08.08.2026 08:15',
    bugunku_aktif_siparis: 9,
    gunluk_ortalama_hacim: 64,
    toplam_paket: 980,
    toplam_teslim: 941,
    toplam_iptal: 18,
    teslimat_basari_orani: 96.4,
    ortalama_gorev_suresi_dk: 22,
    kayit_tarihi: '03.03.2025 14:05',
    il: 'İstanbul',
    ilce: 'Ümraniye',
  }),
  customer({
    id: 'c-trendyol',
    musteri_kodu: 'CUST-1500',
    firma_unvani: 'DSM Grup Danışmanlık İletişim ve Satış Ticaret A.Ş.',
    marka_kisa_ad: 'Trendyol Express',
    vkn: '6310548468',
    vergi_dairesi: 'Maslak',
    durum: 'aktif',
    sektor: 'E-Ticaret',
    entegrasyon_tipi: 'API',
    ana_yetkili: 'Can Arslan',
    ana_yetkili_unvan: 'Last Mile Partner',
    telefon: '+90 212 900 0000',
    email: 'partner@trendyol.com',
    fatura_merkez_adresi: 'Maslak Mh. Büyükdere Cd. No:237, Sarıyer / İstanbul',
    tesis_sayisi: 8,
    merkez_depo_sayisi: 3,
    son_senkronizasyon: '08.08.2026 10:02',
    bugunku_aktif_siparis: 28,
    gunluk_ortalama_hacim: 210,
    toplam_paket: 5400,
    toplam_teslim: 5210,
    toplam_iptal: 95,
    teslimat_basari_orani: 95.8,
    ortalama_gorev_suresi_dk: 16,
    kayit_tarihi: '18.11.2024 09:00',
    il: 'İstanbul',
    ilce: 'Sarıyer',
  }),
  customer({
    id: 'c-hb',
    musteri_kodu: 'CUST-1310',
    firma_unvani: 'D-Market Elektronik Hizmetler Tic. A.Ş.',
    marka_kisa_ad: 'Hepsiburada',
    vkn: '2650542980',
    vergi_dairesi: 'Şişli',
    durum: 'aktif',
    sektor: 'E-Ticaret',
    entegrasyon_tipi: 'API',
    ana_yetkili: 'İrem Polat',
    ana_yetkili_unvan: 'Teslimat Operasyon',
    telefon: '+90 850 222 4444',
    email: 'delivery@hepsiburada.com',
    fatura_merkez_adresi: 'Kuştepe Mh. Mecidiyeköy Yolu Cd. No:12, Şişli / İstanbul',
    tesis_sayisi: 6,
    merkez_depo_sayisi: 2,
    son_senkronizasyon: '08.08.2026 07:55',
    bugunku_aktif_siparis: 17,
    gunluk_ortalama_hacim: 150,
    toplam_paket: 3200,
    toplam_teslim: 3088,
    toplam_iptal: 54,
    teslimat_basari_orani: 96.9,
    ortalama_gorev_suresi_dk: 17,
    kayit_tarihi: '22.02.2025 16:40',
    il: 'İstanbul',
    ilce: 'Şişli',
  }),
  customer({
    id: 'c-getir',
    musteri_kodu: 'CUST-1201',
    firma_unvani: 'Getir Perakende Lojistik A.Ş.',
    marka_kisa_ad: 'Getir',
    vkn: '3891234567',
    vergi_dairesi: 'Beşiktaş',
    durum: 'aktif',
    sektor: 'Hazır Yemek',
    entegrasyon_tipi: 'API',
    ana_yetkili: 'Deniz Acar',
    ana_yetkili_unvan: 'Dark Store Ops',
    telefon: '+90 850 241 0000',
    email: 'ops@getir.com',
    fatura_merkez_adresi: 'Levent Mh. Büyükdere Cd. No:163, Beşiktaş / İstanbul',
    tesis_sayisi: 12,
    merkez_depo_sayisi: 4,
    son_senkronizasyon: '08.08.2026 10:30',
    bugunku_aktif_siparis: 41,
    gunluk_ortalama_hacim: 320,
    toplam_paket: 8900,
    toplam_teslim: 8610,
    toplam_iptal: 140,
    teslimat_basari_orani: 94.5,
    ortalama_gorev_suresi_dk: 12,
    kayit_tarihi: '05.06.2024 10:10',
    il: 'İstanbul',
    ilce: 'Beşiktaş',
  }),
  customer({
    id: 'c-migros',
    musteri_kodu: 'CUST-1160',
    firma_unvani: 'Migros Ticaret A.Ş.',
    marka_kisa_ad: 'Migros',
    vkn: '6220529014',
    vergi_dairesi: 'Ataşehir',
    durum: 'aktif',
    sektor: 'Gıda',
    entegrasyon_tipi: 'XML',
    ana_yetkili: 'Selin Ak',
    ana_yetkili_unvan: 'E-Ticaret Lojistik',
    telefon: '+90 216 700 0000',
    email: 'lastmile@migros.com',
    fatura_merkez_adresi: 'Atatürk Mah. Turgut Özal Bulvarı No:7, Ataşehir / İstanbul',
    tesis_sayisi: 4,
    merkez_depo_sayisi: 2,
    son_senkronizasyon: '07.08.2026 22:10',
    bugunku_aktif_siparis: 6,
    gunluk_ortalama_hacim: 48,
    toplam_paket: 760,
    toplam_teslim: 734,
    toplam_iptal: 11,
    teslimat_basari_orani: 98.1,
    ortalama_gorev_suresi_dk: 25,
    kayit_tarihi: '14.08.2025 13:25',
    il: 'İstanbul',
    ilce: 'Ataşehir',
  }),
  customer({
    id: 'c-vivense',
    musteri_kodu: 'CUST-1422',
    firma_unvani: 'Vivense Teknoloji Hizmetleri ve Ticaret A.Ş.',
    marka_kisa_ad: 'Vivense',
    vkn: '9250411122',
    vergi_dairesi: 'Maltepe',
    durum: 'aktif',
    sektor: 'Perakende',
    entegrasyon_tipi: 'Shopify',
    ana_yetkili: 'Burak Şen',
    ana_yetkili_unvan: 'Kurulum Operasyon',
    telefon: '+90 216 333 2211',
    email: 'teslimat@vivense.com',
    fatura_merkez_adresi: 'Cevizli Mah. Tugay Yolu Cd. No:69, Maltepe / İstanbul',
    tesis_sayisi: 2,
    merkez_depo_sayisi: 1,
    son_senkronizasyon: '08.08.2026 06:40',
    bugunku_aktif_siparis: 4,
    gunluk_ortalama_hacim: 22,
    toplam_paket: 410,
    toplam_teslim: 392,
    toplam_iptal: 9,
    teslimat_basari_orani: 95.1,
    ortalama_gorev_suresi_dk: 45,
    kayit_tarihi: '29.09.2025 11:55',
    il: 'İstanbul',
    ilce: 'Maltepe',
  }),
  customer({
    id: 'c-xrest',
    musteri_kodu: 'CUST-1099',
    firma_unvani: 'X Restaurant Gıda ve Restoran Hizmetleri Ltd. Şti.',
    marka_kisa_ad: 'X Restaurant',
    vkn: '7744553322',
    vergi_dairesi: 'Beşiktaş',
    durum: 'aktif',
    sektor: 'Hazır Yemek',
    entegrasyon_tipi: 'Manuel',
    ana_yetkili: 'Mert Ak',
    ana_yetkili_unvan: 'Şube Müdürü',
    telefon: '+90 212 555 7788',
    email: 'siparis@xrestaurant.com',
    fatura_merkez_adresi: 'Abbasağa Mah. Spor Cd. No:4, Beşiktaş / İstanbul',
    tesis_sayisi: 2,
    merkez_depo_sayisi: 0,
    son_senkronizasyon: '—',
    bugunku_aktif_siparis: 3,
    gunluk_ortalama_hacim: 18,
    toplam_paket: 260,
    toplam_teslim: 248,
    toplam_iptal: 7,
    teslimat_basari_orani: 93.8,
    ortalama_gorev_suresi_dk: 28,
    kayit_tarihi: '11.04.2026 09:30',
    il: 'İstanbul',
    ilce: 'Beşiktaş',
  }),
  customer({
    id: 'c-mm',
    musteri_kodu: 'CUST-1555',
    firma_unvani: 'MediaMarkt Saturn Türkiye Ticaret Ltd. Şti.',
    marka_kisa_ad: 'MediaMarkt',
    vkn: '6130523344',
    vergi_dairesi: 'Üsküdar',
    durum: 'pasif',
    sektor: 'Teknoloji',
    entegrasyon_tipi: 'XML',
    ana_yetkili: 'Gökhan Demir',
    ana_yetkili_unvan: 'Mağaza Lojistik',
    telefon: '+90 216 222 3344',
    email: 'lojistik@mediamarkt.com.tr',
    fatura_merkez_adresi: 'Altunizade Mah. Kısıklı Cd. No:22, Üsküdar / İstanbul',
    tesis_sayisi: 3,
    merkez_depo_sayisi: 1,
    son_senkronizasyon: '01.06.2026 18:00',
    bugunku_aktif_siparis: 0,
    gunluk_ortalama_hacim: 0,
    toplam_paket: 540,
    toplam_teslim: 510,
    toplam_iptal: 15,
    teslimat_basari_orani: 94.4,
    ortalama_gorev_suresi_dk: 35,
    kayit_tarihi: '07.01.2025 15:10',
    il: 'İstanbul',
    ilce: 'Üsküdar',
  }),
  customer({
    id: 'c-amz',
    musteri_kodu: 'CUST-1600',
    firma_unvani: 'Amazon Turkey Perakende Hizmetleri Ltd. Şti.',
    marka_kisa_ad: 'Amazon',
    vkn: '0680933858',
    vergi_dairesi: 'Çekmeköy',
    durum: 'aktif',
    sektor: 'E-Ticaret',
    entegrasyon_tipi: 'API',
    ana_yetkili: 'Zeynep Arslan',
    ana_yetkili_unvan: 'DSP Partner',
    telefon: '+90 850 222 6269',
    email: 'tr-dsp@amazon.com',
    fatura_merkez_adresi: 'Alemdağ Cd. No:188, Çekmeköy / İstanbul',
    tesis_sayisi: 4,
    merkez_depo_sayisi: 2,
    son_senkronizasyon: '08.08.2026 09:05',
    bugunku_aktif_siparis: 14,
    gunluk_ortalama_hacim: 95,
    toplam_paket: 2100,
    toplam_teslim: 2015,
    toplam_iptal: 40,
    teslimat_basari_orani: 96.0,
    ortalama_gorev_suresi_dk: 20,
    kayit_tarihi: '20.05.2025 12:00',
    il: 'İstanbul',
    ilce: 'Çekmeköy',
  }),
]

export function getCustomerListKpiMock() {
  return buildCustomerKpi(mockCustomerList)
}

export function getCustomerStatusCountsMock() {
  return countCustomersByStatusScope(mockCustomerList)
}
