/* ------------------------------------------------------------------ */
/*  Taşıma Detay – Mock Veri                                           */
/* ------------------------------------------------------------------ */

import type { TasimaDetayRecord } from "../_types/transport-detail"

export const mockTasimaDetaylar: TasimaDetayRecord[] = [
  {
    tasimaNo: "TSM-20000001",
    tarih: "15.01.2025",
    rota: "Adana → Kocaeli",
    olusturan: "Operasyon Merkezi",
    gondericiLokasyon: "Adana / Seyhan",
    gondericiSube: "Adana Seyhan Şube",
    gonderiTipi: "FTL",
    aracTipi: "Tır",
    surucuAdi: "Ahmet Yılmaz",
    aracPlaka: "34 ABC 123",
    durum: "teslim_edildi",
    durumLabel: "Teslim Edildi",

    gondericiMusteri: {
      customerId: "CUS-001",
      customerType: "individual",
      displayName: "AHMET KARAN",
      contactName: "Ahmet Karan",
      tcIdentityNumber: "12345678901",
      phone: "05321234567",
      email: "ahmet.karan@email.com",
      branch: "Adana Seyhan Şube",
      city: "Adana",
      district: "Seyhan",
      neighborhood: "Kurtuluş Mahallesi",
      fullAddress: "Kurtuluş Mah. Atatürk Cad. No:45 Seyhan / Adana",
    },
    aliciMusteri: {
      customerId: "CUS-002",
      customerType: "corporate",
      displayName: "DELTA TİCARET LTD.",
      companyName: "DELTA TİCARET LTD. ŞTİ.",
      contactName: "Serdar Yıldırım",
      taxNumber: "1234567890",
      taxOffice: "Gebze Vergi Dairesi",
      phone: "02621234567",
      email: "info@deltaticaretltd.com",
      branch: "Kocaeli Gebze Şube",
      city: "Kocaeli",
      district: "Gebze",
      neighborhood: "OSB Mahallesi",
      fullAddress: "Gebze OSB 5. Cadde No:22 Gebze / Kocaeli",
    },
    tedarikci: {
      supplierId: "SUP-001",
      firmaAdi: "DELTA TEDARİK",
      sehir: "İstanbul",
      yetkili: "Mehmet Yılmaz",
      unvan: "Operasyon Müdürü",
      telefon: "+90 212 555 00 01",
      email: "info@deltatedarik.com.tr",
      aracPlaka: "34 ABC 123",
      aracTipi: "Tır",
      kasaTipi: "Tenteli",
      maxAgirlikKapasitesi: 25000,
      maxHacimKapasitesi: 90,
      surucuAd: "Ahmet",
      surucuSoyad: "Yılmaz",
      surucuTelefon: "+90 533 111 22 33",
    },
    operasyonSorumlusu: {
      userId: "USR-101",
      adSoyad: "Serkan Kandemir",
      rol: "Operasyon Yöneticisi",
      telefon: "+90 532 678 90 12",
      email: "serkan.kandemir@arf.com.tr",
    },
    satisSorumlusu: {
      userId: "USR-102",
      adSoyad: "Sinan Işık",
      rol: "Satış Temsilcisi",
      telefon: "+90 541 345 67 89",
      email: "sinan.isik@arf.com.tr",
    },

    mevcutAdim: 8,
    toplamAdim: 8,
    adimlar: [
      { adimNo: 1, baslik: "Taşıma Oluşturuldu", aciklama: "Operasyon Merkezi tarafından taşıma oluşturuldu. (14:30)", tamamlandi: true, aktif: false, zaman: "14:30" },
      { adimNo: 2, baslik: "Sürücü Atandı", aciklama: "Sürücü Ahmet Yılmaz atandı.", tamamlandi: true, aktif: false },
      { adimNo: 3, baslik: "Sürücü Alım Adresine Gidiyor", aciklama: "Sürücü Adana'ya doğru yola çıktı.", tamamlandi: true, aktif: false },
      { adimNo: 4, baslik: "Yükleme Yapılıyor", aciklama: "20 palet yükleme başlatıldı.", tamamlandi: true, aktif: false },
      { adimNo: 5, baslik: "Yolda", aciklama: "Araç Adana'dan çıkış yaptı, Kocaeli'ye doğru ilerliyor.", tamamlandi: true, aktif: false },
      { adimNo: 6, baslik: "Teslim Noktasına Ulaşıldı", aciklama: "Araç Gebze'ye ulaştı.", tamamlandi: true, aktif: false },
      { adimNo: 7, baslik: "Boşaltma Yapılıyor", aciklama: "Boşaltma işlemi tamamlandı.", tamamlandi: true, aktif: false },
      { adimNo: 8, baslik: "Teslim Edildi", aciklama: "Yükler teslim edildi. Teslim alan: Serdar Yıldırım", tamamlandi: true, aktif: false },
    ],

    ftlOperasyon: {
      tarih: "15/01/2025",
      gondericiMusteri: "Ahmet Karan",
      aliciMusteri: "Serdar Yıldırım",
      cikisAdresi: "Kurtuluş Mah. Atatürk Cad. No:45 Seyhan / Adana",
      varisAdresi: "Gebze OSB 5. Cadde No:22 Gebze / Kocaeli",
    },

    yukler: [
      { id: "yuk-1", yukTipi: "Palet", adet: 20, en: 120, boy: 80, genislik: 150, agirlik: 18000 },
    ],

    fiyatlandirma: {
      satisFiyat: 42000,
      satisKdvOran: 20,
      satisFiyatDetay: {
        birimFiyat: 42000,
        araToplam: 42000,
        tevfikatTutari: 1680,
        ekHizmetTutari: 0,
        kdvTutari: 8400,
        toplamFiyat: 48720,
      },
      alisFiyat: 35000,
      alisKdvOran: 20,
      alisFiyatDetay: {
        birimFiyat: 35000,
        araToplam: 35000,
        tevfikatTutari: 1400,
        ekHizmetTutari: 0,
        kdvTutari: 7000,
        toplamFiyat: 40600,
      },
      ozet: {
        birimFiyat: 42000,
        araToplam: 42000,
        tevfikatTutari: 1680,
      },
    },

    gelirler: [
      { id: "g-1", aciklama: "Taşıma Ücreti (Satış)", musteri: "AHMET KARAN", tarih: "15.01.2025", birimFiyat: 42000, tevkifat: "2/10", tevfikatTutar: 1680, kdvOran: 20, kdvTutar: 8400, toplamTutar: 48720, faturaDurumu: "olusturuldu", tahsilatDurumu: "tahsil_edildi" },
    ],
    giderler: [
      { id: "gd-1", aciklama: "Taşıma Ücreti (Alış)", tedarikci: "DELTA TEDARİK", tarih: "15.01.2025", birimFiyat: 35000, tevkifat: "2/10", tevfikatTutar: 1400, kdvOran: 20, kdvTutar: 7000, toplamTutar: 40600, faturaDurumu: "eslestirildi", odemeDurumu: "odendi" },
    ],
    faturalar: [
      { id: "f-1", faturaTipi: "satis", faturaIsmi: "Adana-Kocaeli Satış Faturası", faturaNo: "FTR-2025-001234", kesimTarihi: "15.01.2025", vadeTarihi: "15.02.2025", mulesteri: "AHMET KARAN", matrah: 42000, tevkifat: 1680, kdvTutar: 8400, toplamTutar: 48720, odenenTutar: 48720, kalanTutar: 0, kategori: "Taşıma", etiketler: ["Sevkiyat", "FTL"], durum: "odendi" },
      { id: "f-2", faturaTipi: "alis", faturaIsmi: "Delta Tedarik Alış Faturası", faturaNo: "GDR-2025-005678", kesimTarihi: "16.01.2025", vadeTarihi: "16.02.2025", mulesteri: "DELTA TEDARİK", matrah: 35000, tevkifat: 1400, kdvTutar: 7000, toplamTutar: 40600, odenenTutar: 40600, kalanTutar: 0, kategori: "Taşıma", etiketler: ["Tedarikçi"], durum: "odendi" },
    ],

    musteriTeklifler: [
      { id: "mt-1", musteri: "Ahmet Karan", oncekiTeklif: 45000, yeniTeklif: 42000, sonuc: "kabul_edildi" },
    ],
    tasimaTeklifler: [
      { id: "tt-1", musteri: "Delta Tedarik", oncekiTeklif: 38000, yeniTeklif: 35000, sonuc: "kabul_edildi" },
    ],
  },
  {
    tasimaNo: "TSM-20000002",
    tarih: "18.01.2025",
    rota: "Ankara → İzmir",
    olusturan: "Operasyon Merkezi",
    gondericiLokasyon: "Ankara / Sincan",
    gondericiSube: "Ankara Şube",
    gonderiTipi: "LTL",
    aracTipi: "Tır",
    surucuAdi: "Ali Kaya",
    aracPlaka: "06 GHI 789",
    durum: "yolda",
    durumLabel: "Yolda",

    gondericiMusteri: {
      customerId: "CUS-003",
      customerType: "corporate",
      displayName: "YILDIZ GIDA SAN.",
      companyName: "YILDIZ GIDA SANAYİ A.Ş.",
      contactName: "Mert Yılmaz",
      taxNumber: "1234567890",
      taxOffice: "Sincan Vergi Dairesi",
      phone: "05069876543",
      email: "info@yildizgida.com",
      branch: "Ankara Şube",
      city: "Ankara",
      district: "Sincan",
      neighborhood: "OSB Mahallesi",
      fullAddress: "Sincan OSB 3. Cadde No:12 Ankara",
    },
    aliciMusteri: {
      customerId: "CUS-004",
      customerType: "corporate",
      displayName: "MEGA DEPOLAMA A.Ş.",
      companyName: "MEGA DEPOLAMA A.Ş.",
      contactName: "Elif Arslan",
      taxNumber: "9876543210",
      taxOffice: "Kemalpaşa Vergi Dairesi",
      phone: "05451112233",
      email: "info@megadepo.com",
      branch: "İzmir Şube",
      city: "İzmir",
      district: "Kemalpaşa",
      neighborhood: "OSB Mahallesi",
      fullAddress: "Kemalpaşa OSB No:8 İzmir",
    },
    tedarikci: {
      supplierId: "SUP-002",
      firmaAdi: "MARS LOJİSTİK",
      sehir: "Ankara",
      yetkili: "Hasan Demir",
      unvan: "Filo Sorumlusu",
      telefon: "+90 312 444 55 66",
      email: "info@marslojistik.com.tr",
      aracPlaka: "06 GHI 789",
      aracTipi: "Tır",
      kasaTipi: "Tenteli",
      maxAgirlikKapasitesi: 22000,
      maxHacimKapasitesi: 85,
      surucuAd: "Ali",
      surucuSoyad: "Kaya",
      surucuTelefon: "+90 544 222 33 44",
    },
    operasyonSorumlusu: {
      userId: "USR-101",
      adSoyad: "Serkan Kandemir",
      rol: "Operasyon Yöneticisi",
      telefon: "+90 532 678 90 12",
      email: "serkan.kandemir@arf.com.tr",
    },
    satisSorumlusu: {
      userId: "USR-102",
      adSoyad: "Sinan Işık",
      rol: "Satış Temsilcisi",
      telefon: "+90 541 345 67 89",
      email: "sinan.isik@arf.com.tr",
    },

    mevcutAdim: 5,
    toplamAdim: 8,
    adimlar: [
      { adimNo: 1, baslik: "Taşıma Oluşturuldu", aciklama: "Sistem tarafından oluşturuldu.", tamamlandi: true, aktif: false },
      { adimNo: 2, baslik: "Sürücü Atandı", aciklama: "Sürücü Ali Kaya atandı.", tamamlandi: true, aktif: false },
      { adimNo: 3, baslik: "Sürücü Alım Adresine Gidiyor", aciklama: "Sürücü yola çıktı.", tamamlandi: true, aktif: false },
      { adimNo: 4, baslik: "Yükleme Yapılıyor", aciklama: "45 parça (Koli + IBC) yükleme tamamlandı.", tamamlandi: true, aktif: false },
      { adimNo: 5, baslik: "Yolda", aciklama: "Araç Ankara'dan çıkış yaptı, İzmir'e doğru ilerliyor.", tamamlandi: false, aktif: true },
      { adimNo: 6, baslik: "Teslim Noktasına Ulaşıldı", aciklama: "Henüz ulaşılmadı.", tamamlandi: false, aktif: false },
      { adimNo: 7, baslik: "Boşaltma Yapılıyor", aciklama: "Henüz başlamadı.", tamamlandi: false, aktif: false },
      { adimNo: 8, baslik: "Teslim Edildi", aciklama: "Henüz teslim edilmedi.", tamamlandi: false, aktif: false },
    ],

    yukler: [
      { id: "yuk-r2-1", yukTipi: "Koli", adet: 45, en: 60, boy: 40, genislik: 30, agirlik: 3200 },
      { id: "yuk-r2-2", yukTipi: "IBC", adet: 10, en: 120, boy: 100, genislik: 116, agirlik: 1200 },
    ],

    fiyatlandirma: {
      satisFiyat: 15500,
      satisKdvOran: 20,
      satisFiyatDetay: {
        birimFiyat: 15500,
        araToplam: 15500,
        tevfikatTutari: 620,
        ekHizmetTutari: 0,
        kdvTutari: 3100,
        toplamFiyat: 17980,
      },
      alisFiyat: 12000,
      alisKdvOran: 20,
      alisFiyatDetay: {
        birimFiyat: 12000,
        araToplam: 12000,
        tevfikatTutari: 480,
        ekHizmetTutari: 0,
        kdvTutari: 2400,
        toplamFiyat: 13920,
      },
      ozet: {
        birimFiyat: 15500,
        araToplam: 15500,
        tevfikatTutari: 620,
      },
    },

    gelirler: [
      { id: "g-r2-1", aciklama: "Taşıma Ücreti (Satış)", musteri: "YILDIZ GIDA SAN.", tarih: "18.01.2025", birimFiyat: 15500, tevkifat: "2/10", tevfikatTutar: 620, kdvOran: 20, kdvTutar: 3100, toplamTutar: 17980, faturaDurumu: "olusturuldu", tahsilatDurumu: "tahsil_edildi" },
    ],
    giderler: [
      { id: "gd-r2-1", aciklama: "Taşıma Ücreti (Alış)", tedarikci: "MARS LOJİSTİK", tarih: "18.01.2025", birimFiyat: 12000, tevkifat: "2/10", tevfikatTutar: 480, kdvOran: 20, kdvTutar: 2400, toplamTutar: 13920, faturaDurumu: "eslestirildi", odemeDurumu: "odendi" },
    ],
    faturalar: [
      { id: "f-r2-1", faturaTipi: "satis", faturaIsmi: "Ankara-İzmir Satış Faturası", faturaNo: "FTR-2025-002345", kesimTarihi: "18.01.2025", vadeTarihi: "18.02.2025", mulesteri: "YILDIZ GIDA SAN.", matrah: 15500, tevkifat: 620, kdvTutar: 3100, toplamTutar: 17980, odenenTutar: 17980, kalanTutar: 0, kategori: "Taşıma", etiketler: ["Sevkiyat", "LTL"], durum: "odendi" },
      { id: "f-r2-2", faturaTipi: "alis", faturaIsmi: "Mars Lojistik Alış Faturası", faturaNo: "GDR-2025-006789", kesimTarihi: "20.01.2025", vadeTarihi: "20.02.2025", mulesteri: "MARS LOJİSTİK", matrah: 12000, tevkifat: 480, kdvTutar: 2400, toplamTutar: 13920, odenenTutar: 13920, kalanTutar: 0, kategori: "Taşıma", etiketler: ["Tedarikçi"], durum: "odendi" },
    ],

    musteriTeklifler: [
      { id: "mt-r2-1", musteri: "Yıldız Gıda", oncekiTeklif: 16000, yeniTeklif: 15500, sonuc: "kabul_edildi" },
    ],
    tasimaTeklifler: [
      { id: "tt-r2-1", musteri: "Mars Lojistik", oncekiTeklif: 13000, yeniTeklif: 12000, sonuc: "kabul_edildi" },
    ],
  },
  {
    tasimaNo: "TSM-20000003",
    tarih: "20.01.2025",
    rota: "Kocaeli → Adana",
    olusturan: "Operasyon Merkezi",
    gondericiLokasyon: "Kocaeli / Gebze",
    gondericiSube: "Kocaeli Gebze Şube",
    gonderiTipi: "FTL",
    aracTipi: "Tır",
    surucuAdi: "Emre Koç",
    aracPlaka: "35 MNO 345",
    durum: "yukleme_yapiliyor",
    durumLabel: "Yükleniyor",

    gondericiMusteri: {
      customerId: "CUS-002",
      customerType: "corporate",
      displayName: "DELTA TİCARET LTD.",
      companyName: "DELTA TİCARET LTD. ŞTİ.",
      contactName: "Serdar Yıldırım",
      taxNumber: "1234567890",
      taxOffice: "Gebze Vergi Dairesi",
      phone: "02621234567",
      email: "info@deltaticaretltd.com",
      branch: "Kocaeli Gebze Şube",
      city: "Kocaeli",
      district: "Gebze",
      neighborhood: "OSB Mahallesi",
      fullAddress: "Gebze OSB 5. Cadde No:22 Gebze / Kocaeli",
    },
    aliciMusteri: {
      customerId: "CUS-001",
      customerType: "individual",
      displayName: "AHMET KARAN",
      contactName: "Ahmet Karan",
      tcIdentityNumber: "12345678901",
      phone: "05321234567",
      email: "ahmet.karan@email.com",
      branch: "Adana Seyhan Şube",
      city: "Adana",
      district: "Seyhan",
      neighborhood: "Kurtuluş Mahallesi",
      fullAddress: "Kurtuluş Mah. Atatürk Cad. No:45 Seyhan / Adana",
    },
    tedarikci: {
      supplierId: "SUP-003",
      firmaAdi: "STAR TAŞIMACILIK",
      sehir: "İzmir",
      yetkili: "Kemal Aydın",
      unvan: "Filo Sorumlusu",
      telefon: "+90 232 333 44 55",
      email: "info@startasimacilik.com.tr",
      aracPlaka: "35 MNO 345",
      aracTipi: "Tır",
      kasaTipi: "Frigo",
      maxAgirlikKapasitesi: 24000,
      maxHacimKapasitesi: 80,
      surucuAd: "Emre",
      surucuSoyad: "Koç",
      surucuTelefon: "+90 545 333 44 55",
    },
    operasyonSorumlusu: {
      userId: "USR-101",
      adSoyad: "Serkan Kandemir",
      rol: "Operasyon Yöneticisi",
      telefon: "+90 532 678 90 12",
      email: "serkan.kandemir@arf.com.tr",
    },
    satisSorumlusu: {
      userId: "USR-102",
      adSoyad: "Sinan Işık",
      rol: "Satış Temsilcisi",
      telefon: "+90 541 345 67 89",
      email: "sinan.isik@arf.com.tr",
    },

    mevcutAdim: 4,
    toplamAdim: 8,
    adimlar: [
      { adimNo: 1, baslik: "Taşıma Oluşturuldu", aciklama: "Operasyon Merkezi tarafından taşıma oluşturuldu. (16:45)", tamamlandi: true, aktif: false, zaman: "16:45" },
      { adimNo: 2, baslik: "Sürücü Atandı", aciklama: "Sürücü Emre Koç atandı.", tamamlandi: true, aktif: false },
      { adimNo: 3, baslik: "Sürücü Alım Adresine Gidiyor", aciklama: "Sürücü Gebze'ye doğru yola çıktı.", tamamlandi: true, aktif: false },
      { adimNo: 4, baslik: "Yükleme Yapılıyor", aciklama: "Palet ve bidon yükleme devam ediyor.", tamamlandi: false, aktif: true },
      { adimNo: 5, baslik: "Yolda", aciklama: "Henüz yola çıkmadı.", tamamlandi: false, aktif: false },
      { adimNo: 6, baslik: "Teslim Noktasına Ulaşıldı", aciklama: "Henüz ulaşılmadı.", tamamlandi: false, aktif: false },
      { adimNo: 7, baslik: "Boşaltma Yapılıyor", aciklama: "Henüz başlamadı.", tamamlandi: false, aktif: false },
      { adimNo: 8, baslik: "Teslim Edildi", aciklama: "Henüz teslim edilmedi.", tamamlandi: false, aktif: false },
    ],

    ftlOperasyon: {
      tarih: "20/01/2025",
      gondericiMusteri: "Serdar Yıldırım",
      aliciMusteri: "Ahmet Karan",
      cikisAdresi: "Gebze OSB 5. Cadde No:22 Gebze / Kocaeli",
      varisAdresi: "Kurtuluş Mah. Atatürk Cad. No:45 Seyhan / Adana",
    },

    yukler: [
      { id: "yuk-r3-1", yukTipi: "Palet", adet: 10, en: 120, boy: 80, genislik: 150, agirlik: 16000 },
      { id: "yuk-r3-2", yukTipi: "Bidon", adet: 5, en: 60, boy: 60, genislik: 90, agirlik: 6000 },
    ],

    fiyatlandirma: {
      satisFiyat: 48000,
      satisKdvOran: 20,
      satisFiyatDetay: {
        birimFiyat: 48000,
        araToplam: 48000,
        tevfikatTutari: 1920,
        ekHizmetTutari: 0,
        kdvTutari: 9600,
        toplamFiyat: 55680,
      },
      alisFiyat: 40000,
      alisKdvOran: 20,
      alisFiyatDetay: {
        birimFiyat: 40000,
        araToplam: 40000,
        tevfikatTutari: 1600,
        ekHizmetTutari: 0,
        kdvTutari: 8000,
        toplamFiyat: 46400,
      },
      ozet: {
        birimFiyat: 48000,
        araToplam: 48000,
        tevfikatTutari: 1920,
      },
    },

    gelirler: [
      { id: "g-r3-1", aciklama: "Taşıma Ücreti (Satış)", musteri: "DELTA TİCARET LTD.", tarih: "20.01.2025", birimFiyat: 48000, tevkifat: "2/10", tevfikatTutar: 1920, kdvOran: 20, kdvTutar: 9600, toplamTutar: 55680, faturaDurumu: "olusturulmadi", tahsilatDurumu: "bekliyor" },
    ],
    giderler: [
      { id: "gd-r3-1", aciklama: "Taşıma Ücreti (Alış)", tedarikci: "STAR TAŞIMACILIK", tarih: "20.01.2025", birimFiyat: 40000, tevkifat: "2/10", tevfikatTutar: 1600, kdvOran: 20, kdvTutar: 8000, toplamTutar: 46400, faturaDurumu: "eslestirilmedi", odemeDurumu: "bekliyor" },
    ],
    faturalar: [],

    musteriTeklifler: [
      { id: "mt-r3-1", musteri: "Delta Ticaret", oncekiTeklif: 50000, yeniTeklif: 48000, sonuc: "kabul_edildi" },
    ],
    tasimaTeklifler: [
      { id: "tt-r3-1", musteri: "Star Taşımacılık", oncekiTeklif: 43000, yeniTeklif: 40000, sonuc: "kabul_edildi" },
    ],
  },
]

/** Taşıma numarasına göre detay kaydı bul */
export function findTasimaDetay(tasimaNo: string): TasimaDetayRecord | undefined {
  return mockTasimaDetaylar.find(
    (r) => r.tasimaNo.toUpperCase().replace(/\s+/g, "") === tasimaNo.toUpperCase().replace(/\s+/g, ""),
  )
}
