import type { BranchEntitlementRow, BranchEntitlementSummary } from "../_types"

// TODO: Remove when API is ready
const rows: BranchEntitlementRow[] = [
  {
    branchId: "branch-antalya",
    branchName: "Antalya Şube",
    branchCode: "ANT-001",
    alimHakedisOrani: 0.2,
    dagitimHakedisOrani: 0.25,
    alimHakedisCirosu: 62250,
    alimHakedisTotal: 12450,
    dagitimHakedisCirosu: 33280,
    dagitimHakedisTotal: 8320,
    toplamHakedis: 20770,
    teslimatiBeklenen: 3150,
    iptalEdilen: 1450,
  },
  {
    branchId: "branch-mersin",
    branchName: "Mersin Şube",
    branchCode: "MRS-002",
    alimHakedisOrani: 0.18,
    dagitimHakedisOrani: 0.22,
    alimHakedisCirosu: 54444,
    alimHakedisTotal: 9800,
    dagitimHakedisCirosu: 27727,
    dagitimHakedisTotal: 6100,
    toplamHakedis: 15900,
    teslimatiBeklenen: 2400,
    iptalEdilen: 1400,
  },
  {
    branchId: "branch-istanbul-avr",
    branchName: "İstanbul Avrupa Şube",
    branchCode: "IST-003",
    alimHakedisOrani: 0.22,
    dagitimHakedisOrani: 0.28,
    alimHakedisCirosu: 129545,
    alimHakedisTotal: 28500,
    dagitimHakedisCirosu: 68571,
    dagitimHakedisTotal: 19200,
    toplamHakedis: 47700,
    teslimatiBeklenen: 7200,
    iptalEdilen: 3200,
  },
  {
    branchId: "branch-istanbul-anadolu",
    branchName: "İstanbul Anadolu Şube",
    branchCode: "IST-004",
    alimHakedisOrani: 0.2,
    dagitimHakedisOrani: 0.25,
    alimHakedisCirosu: 111500,
    alimHakedisTotal: 22300,
    dagitimHakedisCirosu: 63200,
    dagitimHakedisTotal: 15800,
    toplamHakedis: 38100,
    teslimatiBeklenen: 5400,
    iptalEdilen: 3600,
  },
  {
    branchId: "branch-ankara",
    branchName: "Ankara Şube",
    branchCode: "ANK-005",
    alimHakedisOrani: 0.19,
    dagitimHakedisOrani: 0.24,
    alimHakedisCirosu: 95789,
    alimHakedisTotal: 18200,
    dagitimHakedisCirosu: 51667,
    dagitimHakedisTotal: 12400,
    toplamHakedis: 30600,
    teslimatiBeklenen: 4800,
    iptalEdilen: 3000,
  },
  {
    branchId: "branch-izmir",
    branchName: "İzmir Şube",
    branchCode: "IZM-006",
    alimHakedisOrani: 0.21,
    dagitimHakedisOrani: 0.26,
    alimHakedisCirosu: 74286,
    alimHakedisTotal: 15600,
    dagitimHakedisCirosu: 39231,
    dagitimHakedisTotal: 10200,
    toplamHakedis: 25800,
    teslimatiBeklenen: 3900,
    iptalEdilen: 2700,
  },
  {
    branchId: "branch-bursa",
    branchName: "Bursa Şube",
    branchCode: "BRS-007",
    alimHakedisOrani: 0.17,
    dagitimHakedisOrani: 0.21,
    alimHakedisCirosu: 52353,
    alimHakedisTotal: 8900,
    dagitimHakedisCirosu: 26667,
    dagitimHakedisTotal: 5600,
    toplamHakedis: 14500,
    teslimatiBeklenen: 2100,
    iptalEdilen: 1400,
  },
  {
    branchId: "branch-adana",
    branchName: "Adana Şube",
    branchCode: "ADN-008",
    alimHakedisOrani: 0.18,
    dagitimHakedisOrani: 0.23,
    alimHakedisCirosu: 62222,
    alimHakedisTotal: 11200,
    dagitimHakedisCirosu: 32174,
    dagitimHakedisTotal: 7400,
    toplamHakedis: 18600,
    teslimatiBeklenen: 2800,
    iptalEdilen: 1600,
  },
  {
    branchId: "branch-gaziantep",
    branchName: "Gaziantep Şube",
    branchCode: "GAZ-009",
    alimHakedisOrani: 0.16,
    dagitimHakedisOrani: 0.2,
    alimHakedisCirosu: 45000,
    alimHakedisTotal: 7200,
    dagitimHakedisCirosu: 24000,
    dagitimHakedisTotal: 4800,
    toplamHakedis: 12000,
    teslimatiBeklenen: 1800,
    iptalEdilen: 1300,
  },
  {
    branchId: "branch-konya",
    branchName: "Konya Şube",
    branchCode: "KON-010",
    alimHakedisOrani: 0.15,
    dagitimHakedisOrani: 0.19,
    alimHakedisCirosu: 42667,
    alimHakedisTotal: 6400,
    dagitimHakedisCirosu: 20526,
    dagitimHakedisTotal: 3900,
    toplamHakedis: 10300,
    teslimatiBeklenen: 1500,
    iptalEdilen: 1000,
  },
]

function cloneRow(row: BranchEntitlementRow): BranchEntitlementRow {
  return { ...row }
}

export function getBranchEntitlementRows(): BranchEntitlementRow[] {
  return rows.map(cloneRow).sort((a, b) => b.toplamHakedis - a.toplamHakedis)
}

export function getBranchEntitlementSummary(): BranchEntitlementSummary {
  const base = rows.reduce(
    (acc, row) => ({
      toplamHakedis: acc.toplamHakedis + row.toplamHakedis,
      alimHakedisTotal: acc.alimHakedisTotal + row.alimHakedisTotal,
      dagitimHakedisTotal: acc.dagitimHakedisTotal + row.dagitimHakedisTotal,
      teslimatiBeklenen: acc.teslimatiBeklenen + row.teslimatiBeklenen,
      iptalEdilen: acc.iptalEdilen + row.iptalEdilen,
    }),
    {
      toplamHakedis: 0,
      alimHakedisTotal: 0,
      dagitimHakedisTotal: 0,
      teslimatiBeklenen: 0,
      iptalEdilen: 0,
    },
  )
  return {
    ...base,
    netToplamHakedis: base.toplamHakedis - base.teslimatiBeklenen - base.iptalEdilen,
  }
}
