import type { LastmileVehicle, VehicleListKpi, VehicleStatusScope } from '../_types/vehicle'

const defaults = {
  vardiya_baslangic: '09:00',
  vardiya_bitis: '18:00',
  baslangic_stratejisi: 'ilk_gorev' as const,
  park_konumu: null,
  park_lat: null,
  park_lng: null,
  kasko_police_no: null,
  trafik_sigortasi_bitis: null,
  kasko_bitis: null,
  muayene_bitis: null,
  evraklar: [] as LastmileVehicle['evraklar'],
  olusturan: 'Filo Yöneticisi',
  olusturulma_zamani: '01.11.2025 10:00',
  aktif_rota_id: null,
  aktif_rota_label: null,
  aktif_rota_durak_sayisi: null,
  aktif_rota_siparis_sayisi: null,
}

export const VEHICLES_MOCK: LastmileVehicle[] = [
  {
    ...defaults,
    id: 'veh-001',
    plaka: '34 ABC 123',
    durum: 'yolda',
    aktif_rota_id: '4092',
    aktif_rota_label: 'RT-4092',
    aktif_rota_durak_sayisi: 12,
    aktif_rota_siparis_sayisi: 8,
    arac_tipi: 'panelvan',
    kasa_tipi: 'frigo',
    marka: 'Fiat',
    model: 'Fiorino',
    model_yili: 2021,
    zimmetli_surucu_id: 'c-001',
    zimmetli_surucu: 'Mehmet Yılmaz',
    hizmet_bolgesi: 'İstanbul — Şişli / Fulya',
    doluluk_hacim_pct: 85,
    doluluk_agirlik_pct: 40,
    yetenekler: ['soguk_zincir', 'elektrikli'],
    evrak_uyarilari: [
      { kind: 'trafik_sigortasi', label: 'Trafik Sigortası', daysRemaining: 2 },
    ],
    mulkiyet: 'oz_mal',
    max_hacim_m3: 3.2,
    max_agirlik_kg: 650,
    trafik_sigortasi_bitis: '2026-08-01',
    evraklar: [
      {
        id: 'doc-veh-001-ruhsat',
        name: 'ruhsat-34-abc-123.pdf',
        size: 245_760,
        mimeType: 'application/pdf',
        type: 'ruhsat',
        uploadedAt: '2026-01-15T10:30:00.000Z',
        uploadedBy: 'Filo Yöneticisi',
      },
      {
        id: 'doc-veh-001-trafik',
        name: 'trafik-sigortasi-2026.pdf',
        size: 512_000,
        mimeType: 'application/pdf',
        type: 'trafik_sigortasi',
        uploadedAt: '2026-02-01T14:00:00.000Z',
        uploadedBy: 'Filo Yöneticisi',
      },
    ],
  },
  {
    ...defaults,
    id: 'veh-002',
    plaka: '34 DEF 456',
    durum: 'bos_ta',
    arac_tipi: 'panelvan',
    kasa_tipi: 'kapali_kasa',
    marka: 'Ford',
    model: 'Transit Courier',
    model_yili: 2022,
    zimmetli_surucu_id: 'c-002',
    zimmetli_surucu: 'Ayşe Demir',
    hizmet_bolgesi: 'İstanbul — Beşiktaş / Levent',
    doluluk_hacim_pct: 0,
    doluluk_agirlik_pct: 0,
    yetenekler: ['buyuk_hacim'],
    evrak_uyarilari: [],
    mulkiyet: 'oz_mal',
    max_hacim_m3: 4.5,
    max_agirlik_kg: 900,
  },
  {
    ...defaults,
    id: 'veh-003',
    plaka: '34 GHI 789',
    durum: 'pasif',
    aktif_rota_id: null,
    aktif_rota_label: null,
    aktif_rota_durak_sayisi: null,
    aktif_rota_siparis_sayisi: null,
    arac_tipi: 'motosiklet',
    kasa_tipi: null,
    marka: 'Honda',
    model: 'PCX 125',
    model_yili: 2023,
    zimmetli_surucu_id: 'c-003',
    zimmetli_surucu: 'Can Öztürk',
    hizmet_bolgesi: 'İstanbul — Kadıköy / Moda',
    doluluk_hacim_pct: 0,
    doluluk_agirlik_pct: 0,
    yetenekler: ['hizli_teslimat'],
    evrak_uyarilari: [
      { kind: 'muayene', label: 'Araç Muayenesi', daysRemaining: -3 },
    ],
    mulkiyet: 'esnaf_kurye',
    max_hacim_m3: 0.2,
    max_agirlik_kg: 25,
    muayene_bitis: '2026-07-27',
  },
  {
    ...defaults,
    id: 'veh-004',
    plaka: '06 JKL 012',
    durum: 'bos_ta',
    arac_tipi: 'kamyonet',
    kasa_tipi: 'kapali_kasa',
    marka: 'Volkswagen',
    model: 'Caddy',
    model_yili: 2020,
    zimmetli_surucu_id: 'c-004',
    zimmetli_surucu: 'Burak Kaya',
    hizmet_bolgesi: 'Ankara — Çankaya / Kızılay',
    doluluk_hacim_pct: 12,
    doluluk_agirlik_pct: 8,
    yetenekler: ['asansorlu', 'buyuk_hacim'],
    evrak_uyarilari: [
      { kind: 'kasko', label: 'Kasko', daysRemaining: 12 },
    ],
    mulkiyet: 'oz_mal',
    max_hacim_m3: 6.0,
    max_agirlik_kg: 1200,
    baslangic_stratejisi: 'sabit_park',
    park_konumu: 'Çankaya, Ankara',
    park_lat: 39.9208,
    park_lng: 32.8541,
    kasko_police_no: 'KSK-2024-88421',
    kasko_bitis: '2026-08-11',
  },
  {
    ...defaults,
    id: 'veh-005',
    plaka: '35 MNO 345',
    durum: 'pasif',
    arac_tipi: 'minivan',
    kasa_tipi: 'kapali_kasa',
    marka: 'Renault',
    model: 'Trafic',
    model_yili: 2019,
    zimmetli_surucu_id: null,
    zimmetli_surucu: null,
    hizmet_bolgesi: 'İzmir — Bornova / Erzene',
    doluluk_hacim_pct: 0,
    doluluk_agirlik_pct: 0,
    yetenekler: ['adr'],
    evrak_uyarilari: [
      { kind: 'trafik_sigortasi', label: 'Trafik Sigortası', daysRemaining: -15 },
      { kind: 'muayene', label: 'Araç Muayenesi', daysRemaining: 5 },
    ],
    mulkiyet: 'kiralik',
    max_hacim_m3: 8.5,
    max_agirlik_kg: 1400,
  },
  {
    ...defaults,
    id: 'veh-006',
    plaka: '34 PQR 678',
    durum: 'yolda',
    aktif_rota_id: '4011',
    aktif_rota_label: 'RT-4011',
    aktif_rota_durak_sayisi: 15,
    aktif_rota_siparis_sayisi: 11,
    arac_tipi: 'panelvan',
    kasa_tipi: 'frigo',
    marka: 'Mercedes-Benz',
    model: 'Citan',
    model_yili: 2024,
    zimmetli_surucu_id: 'c-005',
    zimmetli_surucu: 'Elif Şahin',
    hizmet_bolgesi: 'İstanbul — Ataşehir / Barbaros',
    doluluk_hacim_pct: 92,
    doluluk_agirlik_pct: 61,
    yetenekler: ['soguk_zincir', 'asansorlu'],
    evrak_uyarilari: [],
    mulkiyet: 'oz_mal',
    max_hacim_m3: 5.0,
    max_agirlik_kg: 1000,
  },
  {
    ...defaults,
    id: 'veh-007',
    plaka: '16 STU 901',
    durum: 'bos_ta',
    arac_tipi: 'motosiklet',
    kasa_tipi: null,
    marka: 'Yamaha',
    model: 'NMAX 155',
    model_yili: 2022,
    zimmetli_surucu_id: 'c-006',
    zimmetli_surucu: 'Deniz Arslan',
    hizmet_bolgesi: 'Bursa — Nilüfer / Özlüce',
    doluluk_hacim_pct: 0,
    doluluk_agirlik_pct: 0,
    yetenekler: ['hizli_teslimat', 'elektrikli'],
    evrak_uyarilari: [],
    mulkiyet: 'esnaf_kurye',
    max_hacim_m3: 0.25,
    max_agirlik_kg: 30,
  },
  {
    ...defaults,
    id: 'veh-008',
    plaka: '34 VWX 234',
    durum: 'bos_ta',
    arac_tipi: 'panelvan',
    kasa_tipi: 'kapali_kasa',
    marka: 'Peugeot',
    model: 'Partner',
    model_yili: 2021,
    zimmetli_surucu_id: 'c-007',
    zimmetli_surucu: 'Hakan Çelik',
    hizmet_bolgesi: 'İstanbul — Ümraniye / Çakmak',
    doluluk_hacim_pct: 28,
    doluluk_agirlik_pct: 35,
    yetenekler: [],
    evrak_uyarilari: [
      { kind: 'trafik_sigortasi', label: 'Trafik Sigortası', daysRemaining: 0 },
    ],
    mulkiyet: 'kiralik',
    max_hacim_m3: 3.8,
    max_agirlik_kg: 750,
  },
  {
    ...defaults,
    id: 'veh-009',
    plaka: '41 YZA 567',
    durum: 'yolda',
    aktif_rota_id: '4120',
    aktif_rota_label: 'RT-4120',
    aktif_rota_durak_sayisi: 9,
    aktif_rota_siparis_sayisi: 6,
    arac_tipi: 'kamyonet',
    kasa_tipi: 'kapali_kasa',
    marka: 'Isuzu',
    model: 'NPR',
    model_yili: 2018,
    zimmetli_surucu_id: 'c-008',
    zimmetli_surucu: 'Serkan Aydın',
    hizmet_bolgesi: 'Kocaeli — Gebze / Dilovası',
    doluluk_hacim_pct: 67,
    doluluk_agirlik_pct: 78,
    yetenekler: ['asansorlu', 'buyuk_hacim', 'adr'],
    evrak_uyarilari: [],
    mulkiyet: 'oz_mal',
    max_hacim_m3: 18,
    max_agirlik_kg: 4500,
  },
  {
    ...defaults,
    id: 'veh-010',
    plaka: '34 BCD 890',
    durum: 'bos_ta',
    arac_tipi: 'minivan',
    kasa_tipi: 'frigo',
    marka: 'Toyota',
    model: 'Proace City',
    model_yili: 2023,
    zimmetli_surucu_id: 'c-009',
    zimmetli_surucu: 'Zeynep Aksoy',
    hizmet_bolgesi: 'İstanbul — Bakırköy / Ataköy',
    doluluk_hacim_pct: 0,
    doluluk_agirlik_pct: 0,
    yetenekler: ['soguk_zincir'],
    evrak_uyarilari: [
      { kind: 'kasko', label: 'Kasko', daysRemaining: 4 },
    ],
    mulkiyet: 'oz_mal',
    max_hacim_m3: 4.2,
    max_agirlik_kg: 850,
  },
  {
    ...defaults,
    id: 'veh-011',
    plaka: '07 EFG 111',
    durum: 'pasif',
    arac_tipi: 'panelvan',
    kasa_tipi: 'kapali_kasa',
    marka: 'Citroën',
    model: 'Berlingo',
    model_yili: 2017,
    zimmetli_surucu_id: null,
    zimmetli_surucu: null,
    hizmet_bolgesi: 'Antalya — Muratpaşa / Lara',
    doluluk_hacim_pct: 0,
    doluluk_agirlik_pct: 0,
    yetenekler: [],
    evrak_uyarilari: [
      { kind: 'muayene', label: 'Araç Muayenesi', daysRemaining: -40 },
      { kind: 'trafik_sigortasi', label: 'Trafik Sigortası', daysRemaining: -8 },
    ],
    mulkiyet: 'kiralik',
    max_hacim_m3: 3.5,
    max_agirlik_kg: 700,
  },
  {
    ...defaults,
    id: 'veh-012',
    plaka: '34 HIJ 222',
    durum: 'yolda',
    aktif_rota_id: '4133',
    aktif_rota_label: 'RT-4133',
    aktif_rota_durak_sayisi: 5,
    aktif_rota_siparis_sayisi: 4,
    arac_tipi: 'motosiklet',
    kasa_tipi: null,
    marka: 'Kymco',
    model: 'Agility 125',
    model_yili: 2024,
    zimmetli_surucu_id: 'c-010',
    zimmetli_surucu: 'Onur Yıldız',
    hizmet_bolgesi: 'İstanbul — Şişli / Fulya',
    doluluk_hacim_pct: 40,
    doluluk_agirlik_pct: 55,
    yetenekler: ['hizli_teslimat'],
    evrak_uyarilari: [],
    mulkiyet: 'esnaf_kurye',
    max_hacim_m3: 0.18,
    max_agirlik_kg: 20,
  },
]

export function computeVehicleKpi(items: LastmileVehicle[]): VehicleListKpi {
  return {
    total: items.length,
    onRoad: items.filter((vehicle) => vehicle.durum === 'yolda').length,
    idle: items.filter((vehicle) => vehicle.durum === 'bos_ta').length,
    passive: items.filter((v) => v.durum === 'pasif').length,
    criticalOccupancy: items.filter(
      (v) => v.doluluk_hacim_pct >= 80 || v.doluluk_agirlik_pct >= 80
    ).length,
    docWarnings: items.filter((v) => v.evrak_uyarilari.length > 0).length,
  }
}

export function computeStatusCounts(
  items: LastmileVehicle[]
): Record<VehicleStatusScope, number> {
  return {
    all: items.length,
    yolda: items.filter((vehicle) => vehicle.durum === 'yolda').length,
    bos_ta: items.filter((vehicle) => vehicle.durum === 'bos_ta').length,
    pasif: items.filter((v) => v.durum === 'pasif').length,
  }
}
