import type { SupplierDetail } from "../_types"

export const supplierDetailMockData: Record<string, SupplierDetail> = {
  "1": {
    id: "1",
    name: "Ekspress24 Kargo",
    supplierType: "ozmal",
    status: "active",
    contractType: "fixed_salary",
    contactPerson: "Ahmet Yılmaz",
    contactPersonTitle: "Operasyon Direktörü",
    contactPhone: "+90 212 555 0001",
    contactEmail: "ahmet.yilmaz@ekspress24.com",
    city: "İstanbul",
    vehicleCount: 12,
    driverCount: 15,
    activeTripsCount: 4,
    totalTripsCount: 1842,
    isDeletable: false,
    isDeactivatable: false,
    hasExpiringDocuments: false,
    createdAt: "2020-01-01",
    updatedAt: "2024-01-15",
    createdBy: "Sistem",
    // Yasal
    taxOffice: "Kadıköy V.D.",
    taxNumber: "1234567890",
    officialAddress: "Atatürk Cad. No:1 Kadıköy / İstanbul",
    // Banka
    iban: "TR12 0001 0017 0000 0001 2345 67",
    accountHolder: "Ekspress24 Kargo A.Ş.",
    // Anlaşma
    paymentTermDays: 30,
    // Araçlar
    vehicles: [
      {
        id: "v1",
        plate: "34 ABC 001",
        brand: "Mercedes",
        model: "Actros",
        bodyType: "tenteli",
        vehicleType: "tir",
        year: 2022,
        maxWeightCapacity: 24,
        maxVolumeCapacity: 68,
        status: "active",
        currentDriverId: "d1",
        currentDriverName: "Mehmet Demir",
        inspectionExpiryDate: "2026-06-01",
        trafficInsuranceExpiryDate: "2026-05-12",
        cascoPolicyNumber: "KSK-34001",
        cascoExpiryDate: "2026-07-01",
        documents: [
          { id: "vd1", type: "ruhsat", label: "Ruhsat", uploadedAt: "2025-01-10", fileUrl: "#" },
          { id: "vd2", type: "trafik_sigortasi", label: "Sigorta Poliçesi", uploadedAt: "2025-02-10", fileUrl: "#" },
        ],
      },
      {
        id: "v2",
        plate: "34 DEF 002",
        brand: "Volvo",
        model: "FH",
        bodyType: "frigorifik",
        vehicleType: "tir",
        year: 2021,
        maxWeightCapacity: 24,
        maxVolumeCapacity: 64,
        status: "active",
        inspectionExpiryDate: "2026-08-15",
        trafficInsuranceExpiryDate: "2026-04-30",
        cascoPolicyNumber: "KSK-34002",
        cascoExpiryDate: "2026-06-20",
        documents: [{ id: "vd3", type: "muayene", label: "Muayene Belgesi", uploadedAt: "2025-03-01", fileUrl: "#" }],
      },
      {
        id: "v3",
        plate: "34 GHI 003",
        brand: "Ford",
        model: "Transit",
        bodyType: "panelvan",
        vehicleType: "van",
        year: 2023,
        maxWeightCapacity: 2,
        maxVolumeCapacity: 14,
        status: "passive",
        inspectionExpiryDate: "2026-01-10",
        trafficInsuranceExpiryDate: "2025-12-01",
        cascoPolicyNumber: "KSK-34003",
        cascoExpiryDate: "2025-12-20",
        documents: [],
      },
    ],
    // Sürücüler
    drivers: [
      {
        id: "d1",
        firstName: "Mehmet",
        lastName: "Demir",
        phone: "+90 532 111 2233",
        nationalId: "12345678901",
        birthDate: "1985-04-12",
        bloodGroup: "A Rh+",
        licenseClass: "CE",
        licenseExpiry: "2026-03-15",
        srcType: "SRC-2",
        hasSrcCertificate: true,
        srcExpiryDate: "2025-09-01",
        psychotechnicExpiryDate: "2026-01-20",
        status: "on_trip",
        activeVehicleId: "v1",
        activeVehiclePlate: "34 ABC 001",
        totalTrips: 412,
        documents: [
          { id: "dd1", type: "ehliyet_fotokopisi", label: "Ehliyet Belgesi", uploadedAt: "2025-01-10", fileUrl: "#" },
          { id: "dd2", type: "src_belgesi", label: "SRC Belgesi", uploadedAt: "2025-01-10", fileUrl: "#" },
        ],
      },
      {
        id: "d2",
        firstName: "Ali",
        lastName: "Kaya",
        phone: "+90 532 222 3344",
        nationalId: "98765432101",
        birthDate: "1990-08-25",
        bloodGroup: "0 Rh+",
        licenseClass: "CE",
        licenseExpiry: "2025-11-20",
        srcType: "SRC-2",
        hasSrcCertificate: true,
        srcExpiryDate: "2024-02-10",
        psychotechnicExpiryDate: "2025-06-15",
        status: "available",
        totalTrips: 287,
        documents: [],
      },
    ],
    // Evraklar
    documents: [
      {
        id: "doc1",
        documentType: "vergi_levhasi",
        label: "Vergi Levhası",
        uploadedAt: "2024-01-10",
        expiryDate: "2025-01-10",
        isExpired: false,
        isExpiringSoon: false,
      },
      {
        id: "doc2",
        documentType: "imza_sirkuleri",
        label: "İmza Sirküleri",
        uploadedAt: "2023-06-01",
        isExpired: false,
        isExpiringSoon: false,
      },
      {
        id: "doc3",
        documentType: "tasima_sozlesmesi",
        label: "Taşıma Sözleşmesi",
        uploadedAt: "2024-01-01",
        expiryDate: "2025-01-01",
        isExpired: false,
        isExpiringSoon: true,
      },
    ],
  },
  "2": {
    id: "2",
    name: "Kuzey Lojistik A.Ş.",
    supplierType: "logistics",
    status: "active",
    contractType: "per_trip",
    contactPerson: "Fatma Şahin",
    contactPersonTitle: "Müşteri Direktörü",
    contactPhone: "+90 312 555 0002",
    contactEmail: "fatma.sahin@kuzeylojistik.com",
    city: "Ankara",
    vehicleCount: 8,
    driverCount: 10,
    activeTripsCount: 2,
    totalTripsCount: 634,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: true,
    createdAt: "2021-03-15",
    updatedAt: "2024-02-01",
    createdBy: "admin",
    taxOffice: "Çankaya V.D.",
    taxNumber: "9876543210",
    officialAddress: "Kızılay Mah. No:5 Çankaya / Ankara",
    iban: "TR98 0001 0017 0000 0009 8765 43",
    accountHolder: "Kuzey Lojistik A.Ş.",
    paymentTermDays: 45,
    pricePerTrip: 2500,
    vehicles: [
      {
        id: "v10",
        plate: "06 XYZ 100",
        brand: "MAN",
        model: "TGX",
        bodyType: "kapali_kasa",
        vehicleType: "tir",
        year: 2020,
        maxWeightCapacity: 22,
        maxVolumeCapacity: 60,
        status: "active",
        inspectionExpiryDate: "2025-12-01",
        trafficInsuranceExpiryDate: "2025-11-10",
        cascoPolicyNumber: "KSK-06100",
        cascoExpiryDate: "2025-11-30",
        documents: [{ id: "vd10", type: "kasko", label: "Kasko Poliçesi", uploadedAt: "2025-01-05", fileUrl: "#" }],
      },
    ],
    drivers: [
      {
        id: "d10",
        firstName: "Hasan",
        lastName: "Çelik",
        phone: "+90 533 444 5566",
        nationalId: "11122233344",
        birthDate: "1982-11-03",
        bloodGroup: "B Rh+",
        licenseClass: "CE",
        licenseExpiry: "2027-05-10",
        srcType: "SRC-2",
        hasSrcCertificate: true,
        srcExpiryDate: "2024-03-15",
        psychotechnicExpiryDate: "2025-03-20",
        status: "on_trip",
        activeVehicleId: "v10",
        activeVehiclePlate: "06 XYZ 100",
        totalTrips: 198,
        documents: [
          { id: "dd10", type: "ehliyet_fotokopisi", label: "Ehliyet Belgesi", uploadedAt: "2024-01-01", fileUrl: "#" },
        ],
      },
    ],
    documents: [
      {
        id: "doc10",
        documentType: "k_belgesi",
        label: "K Belgesi",
        uploadedAt: "2022-01-01",
        expiryDate: "2024-01-01",
        isExpired: true,
        isExpiringSoon: false,
      },
      {
        id: "doc11",
        documentType: "trafik_sigortasi",
        label: "Trafik Sigortası",
        uploadedAt: "2023-08-01",
        expiryDate: "2024-03-01",
        isExpired: false,
        isExpiringSoon: true,
      },
    ],
  },
  "3": {
    id: "3",
    name: "AKSA Lojistik",
    supplierType: "logistics",
    status: "active",
    contractType: "commission",
    contactPerson: "Kemal Arslan",
    contactPersonTitle: "Genel Müdür",
    contactPhone: "+90 232 555 0003",
    contactEmail: "kemal@aksalojistik.com",
    city: "İzmir",
    vehicleCount: 5,
    driverCount: 6,
    activeTripsCount: 1,
    totalTripsCount: 321,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2022-07-01",
    updatedAt: "2024-01-20",
    createdBy: "admin",
    taxOffice: "Konak V.D.",
    taxNumber: "5554443332",
    officialAddress: "Alsancak Mah. No:22 Konak / İzmir",
    paymentTermDays: 30,
    vehicles: [],
    drivers: [],
    documents: [],
  },
  "4": {
    id: "4",
    name: "Bedirhan Nakliyat",
    supplierType: "truck_owner",
    status: "active",
    contractType: "per_trip",
    contactPerson: "Bedirhan Yıldız",
    contactPersonTitle: "Sahip",
    contactPhone: "+90 505 666 7788",
    city: "Bursa",
    vehicleCount: 2,
    driverCount: 2,
    activeTripsCount: 1,
    totalTripsCount: 145,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2022-11-01",
    updatedAt: "2024-01-05",
    createdBy: "admin",
    pricePerTrip: 1800,
    paymentTermDays: 15,
    vehicles: [
      {
        id: "v20",
        plate: "16 BDR 001",
        brand: "DAF",
        model: "XF",
        bodyType: "acik_kasa",
        vehicleType: "kamyon",
        year: 2019,
        maxWeightCapacity: 12,
        maxVolumeCapacity: 36,
        status: "active",
        currentDriverId: "d20",
        currentDriverName: "Bedirhan Yıldız",
        inspectionExpiryDate: "2026-03-01",
        trafficInsuranceExpiryDate: "2025-10-15",
        cascoPolicyNumber: "KSK-16001",
        cascoExpiryDate: "2025-11-05",
        documents: [{ id: "vd20", type: "ruhsat", label: "Ruhsat", uploadedAt: "2024-12-12", fileUrl: "#" }],
      },
    ],
    drivers: [
      {
        id: "d20",
        firstName: "Bedirhan",
        lastName: "Yıldız",
        phone: "+90 505 666 7788",
        nationalId: "55566677788",
        birthDate: "1992-07-14",
        bloodGroup: "AB Rh+",
        licenseClass: "C",
        licenseExpiry: "2028-04-20",
        srcType: "SRC-2",
        hasSrcCertificate: true,
        srcExpiryDate: "2026-04-20",
        psychotechnicExpiryDate: "2026-04-20",
        status: "on_trip",
        activeVehicleId: "v20",
        activeVehiclePlate: "16 BDR 001",
        totalTrips: 145,
        documents: [],
      },
    ],
    documents: [],
  },
  "5": {
    id: "5",
    name: "Çetin Taşımacılık",
    supplierType: "truck_owner",
    status: "active",
    contractType: "per_desi",
    contactPerson: "Cemal Çetin",
    contactPersonTitle: "Sahip",
    contactPhone: "+90 542 777 8899",
    city: "Konya",
    vehicleCount: 1,
    driverCount: 1,
    activeTripsCount: 0,
    totalTripsCount: 89,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: true,
    createdAt: "2023-02-01",
    updatedAt: "2024-02-10",
    createdBy: "admin",
    pricePerDesi: 3.2,
    paymentTermDays: 7,
    vehicles: [
      {
        id: "v30",
        plate: "42 CML 001",
        brand: "Renault",
        model: "D-Series",
        bodyType: "kapali_kasa",
        vehicleType: "kamyon",
        year: 2018,
        maxWeightCapacity: 8,
        maxVolumeCapacity: 22,
        status: "passive",
        inspectionExpiryDate: "2025-02-28",
        trafficInsuranceExpiryDate: "2025-03-15",
        cascoPolicyNumber: "KSK-42001",
        cascoExpiryDate: "2025-04-01",
        documents: [{ id: "vd30", type: "trafik_sigortasi", label: "Trafik Sigortası", uploadedAt: "2024-11-01", fileUrl: "#" }],
      },
    ],
    drivers: [
      {
        id: "d30",
        firstName: "Cemal",
        lastName: "Çetin",
        phone: "+90 542 777 8899",
        nationalId: "33344455566",
        birthDate: "1975-02-28",
        bloodGroup: "0 Rh-",
        licenseClass: "C",
        licenseExpiry: "2024-05-15",
        hasSrcCertificate: false,
        status: "available",
        totalTrips: 89,
        documents: [],
      },
    ],
    documents: [
      {
        id: "doc30",
        documentType: "kasko",
        label: "Kasko",
        uploadedAt: "2023-01-01",
        expiryDate: "2024-01-01",
        isExpired: true,
        isExpiringSoon: false,
      },
    ],
  },
  "6": {
    id: "6",
    name: "Güney Ambar",
    supplierType: "warehouse",
    status: "active",
    contractType: "fixed_salary",
    contactPerson: "Serkan Güneş",
    contactPersonTitle: "Depo Müdürü",
    contactPhone: "+90 322 555 0006",
    contactEmail: "serkan@guneyambar.com",
    city: "Adana",
    vehicleCount: 0,
    driverCount: 0,
    activeTripsCount: 0,
    totalTripsCount: 0,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2023-05-01",
    updatedAt: "2024-01-30",
    createdBy: "admin",
    taxOffice: "Seyhan V.D.",
    taxNumber: "7778889991",
    officialAddress: "Sanayi Mah. Depo Sok. No:15 Seyhan / Adana",
    paymentTermDays: 60,
    vehicles: [],
    drivers: [],
    documents: [
      {
        id: "doc60",
        documentType: "imza_sirkuleri",
        label: "İmza Sirküleri",
        uploadedAt: "2023-05-01",
        isExpired: false,
        isExpiringSoon: false,
      },
    ],
  },
  "7": {
    id: "7",
    name: "Merkez Lojistik",
    supplierType: "logistics",
    status: "passive",
    contractType: "per_trip",
    contactPerson: "Selin Aydın",
    contactPersonTitle: "Yönetici",
    contactPhone: "+90 216 555 0007",
    city: "İstanbul",
    vehicleCount: 3,
    driverCount: 4,
    activeTripsCount: 0,
    totalTripsCount: 256,
    isDeletable: true,
    isDeactivatable: true,
    hasExpiringDocuments: false,
    createdAt: "2021-08-01",
    updatedAt: "2023-11-01",
    createdBy: "admin",
    pricePerTrip: 2200,
    paymentTermDays: 45,
    vehicles: [],
    drivers: [],
    documents: [],
  },
}
