import type { SupplierTransportRecord, SupplierFinancialRecord } from "../_types"

/* ------------------------------------------------------------------ */
/*  Tedarikçi bazlı taşıma kayıtları (gider kalemleri ile)            */
/* ------------------------------------------------------------------ */

export const supplierTransportsMock: Record<string, SupplierTransportRecord[]> = {
  /* ── Ekspress24 Kargo (id:1, özmal) ── */
  "1": [
    {
      id: "str-eks-1",
      tasimaNo: "TSM-20000001",
      yuklemeTarihi: "2026-04-10",
      gonderiTipi: "FTL",
      gondericiMusteri: "AHMET KARAN TİCARET A.Ş.",
      aliciMusteri: "YILDIZ GIDA SAN. VE TİC. LTD. ŞTİ.",
      cikisAdres: "İstanbul / Esenyurt",
      varisAdres: "Ankara / Sincan",
      tedarikciUnvan: "Ekspress24 Kargo",
      aracPlaka: "34 ABC 001",
      surucu: "Mehmet Demir",
      yukler: [{ yukTipi: "Palet", adet: 22, agirlik: 18400 }],
      yukTipleri: "Palet",
      toplamAdet: 22,
      toplamAgirlik: 18400,
      toplamHacim: 52,
      toplamDesi: 13000,
      alisFiyat: 38500,
      durum: "teslim_edildi",
      olusturmaTarihi: "2026-04-09",
      olusturan: "Operasyon Admin",
      giderler: [
        {
          id: "gdr-eks-1-1",
          aciklama: "Taşıma Ücreti",
          tedarikci: "Ekspress24 Kargo",
          tarih: "2026-04-10",
          birimFiyat: 38500,
          tevkifat: "yok",
          tevfikatTutar: 0,
          kdvOran: 20,
          kdvTutar: 7700,
          toplamTutar: 46200,
          faturaDurumu: "eslestirildi",
          odemeDurumu: "odendi",
        },
      ],
    },
    {
      id: "str-eks-2",
      tasimaNo: "TSM-20000005",
      yuklemeTarihi: "2026-04-15",
      gonderiTipi: "FTL",
      gondericiMusteri: "DELTA TİCARET A.Ş.",
      aliciMusteri: "TOPRAK LOJİSTİK A.Ş.",
      cikisAdres: "İstanbul / Tuzla",
      varisAdres: "Bursa / Nilüfer",
      tedarikciUnvan: "Ekspress24 Kargo",
      aracPlaka: "34 DEF 002",
      surucu: "Ali Kaya",
      yukler: [{ yukTipi: "Koli", adet: 140, agirlik: 8200 }],
      yukTipleri: "Koli",
      toplamAdet: 140,
      toplamAgirlik: 8200,
      toplamHacim: 28,
      toplamDesi: 7000,
      alisFiyat: 22000,
      durum: "yolda",
      olusturmaTarihi: "2026-04-14",
      olusturan: "Operasyon Admin",
      giderler: [
        {
          id: "gdr-eks-2-1",
          aciklama: "Taşıma Ücreti",
          tedarikci: "Ekspress24 Kargo",
          tarih: "2026-04-15",
          birimFiyat: 22000,
          tevkifat: "yok",
          tevfikatTutar: 0,
          kdvOran: 20,
          kdvTutar: 4400,
          toplamTutar: 26400,
          faturaDurumu: "eslestirilmedi",
          odemeDurumu: "bekliyor",
        },
        {
          id: "gdr-eks-2-2",
          aciklama: "Köprü Geçiş Ücreti",
          tedarikci: "Ekspress24 Kargo",
          tarih: "2026-04-15",
          birimFiyat: 1500,
          tevkifat: "yok",
          tevfikatTutar: 0,
          kdvOran: 20,
          kdvTutar: 300,
          toplamTutar: 1800,
          faturaDurumu: "eslestirilmedi",
          odemeDurumu: "bekliyor",
        },
      ],
    },
  ],
  /* ── Kuzey Lojistik A.Ş. (id:2) ── */
  "2": [
    {
      id: "str-kzl-1",
      tasimaNo: "TSM-20000003",
      yuklemeTarihi: "2026-04-12",
      gonderiTipi: "FTL",
      gondericiMusteri: "AHMET KARAN TİCARET A.Ş.",
      aliciMusteri: "ARF TEKSTİL SAN. TİC. LTD. ŞTİ.",
      cikisAdres: "İstanbul / Hadımköy",
      varisAdres: "Konya / Selçuklu",
      tedarikciUnvan: "Kuzey Lojistik A.Ş.",
      aracPlaka: "06 XYZ 100",
      surucu: "Hasan Çelik",
      yukler: [
        { yukTipi: "Palet", adet: 16, agirlik: 12800 },
        { yukTipi: "Koli", adet: 40, agirlik: 3200 },
      ],
      yukTipleri: "Palet, Koli",
      toplamAdet: 56,
      toplamAgirlik: 16000,
      toplamHacim: 44,
      toplamDesi: 11000,
      alisFiyat: 55680,
      durum: "yukleniyor",
      olusturmaTarihi: "2026-04-11",
      olusturan: "Harekat Uzmanı",
      giderler: [
        {
          id: "gdr-kzl-1-1",
          aciklama: "Taşıma Ücreti",
          tedarikci: "Kuzey Lojistik A.Ş.",
          tarih: "2026-04-12",
          birimFiyat: 55680,
          tevkifat: "2/10",
          tevfikatTutar: 11136,
          kdvOran: 20,
          kdvTutar: 8908.8,
          toplamTutar: 53452.8,
          faturaDurumu: "eslestirilmedi",
          odemeDurumu: "bekliyor",
        },
        {
          id: "gdr-kzl-1-2",
          aciklama: "Köprü Geçiş Ücreti",
          tedarikci: "Kuzey Lojistik A.Ş.",
          tarih: "2026-04-12",
          birimFiyat: 3000,
          tevkifat: "yok",
          tevfikatTutar: 0,
          kdvOran: 20,
          kdvTutar: 600,
          toplamTutar: 3600,
          faturaDurumu: "eslestirilmedi",
          odemeDurumu: "bekliyor",
        },
      ],
    },
    {
      id: "str-kzl-2",
      tasimaNo: "TSM-20000002",
      yuklemeTarihi: "2026-04-08",
      gonderiTipi: "LTL",
      gondericiMusteri: "YILDIZ GIDA SAN. VE TİC. LTD. ŞTİ.",
      aliciMusteri: "DELTA TİCARET A.Ş.",
      cikisAdres: "Ankara / Çankaya",
      varisAdres: "İzmir / Bornova",
      tedarikciUnvan: "Kuzey Lojistik A.Ş.",
      aracPlaka: "06 XYZ 100",
      surucu: "Hasan Çelik",
      yukler: [{ yukTipi: "Koli", adet: 30, agirlik: 2400 }],
      yukTipleri: "Koli",
      toplamAdet: 30,
      toplamAgirlik: 2400,
      toplamHacim: 12,
      toplamDesi: 3000,
      alisFiyat: 17980,
      durum: "teslim_edildi",
      olusturmaTarihi: "2026-04-07",
      olusturan: "Harekat Uzmanı",
      giderler: [
        {
          id: "gdr-kzl-2-1",
          aciklama: "Taşıma Ücreti",
          tedarikci: "Kuzey Lojistik A.Ş.",
          tarih: "2026-04-08",
          birimFiyat: 17980,
          tevkifat: "yok",
          tevfikatTutar: 0,
          kdvOran: 20,
          kdvTutar: 3596,
          toplamTutar: 21576,
          faturaDurumu: "eslestirildi",
          odemeDurumu: "odendi",
        },
      ],
    },
  ],
  /* ── Bedirhan Nakliyat (id:4) ── */
  "4": [
    {
      id: "str-bdr-1",
      tasimaNo: "TSM-20000004",
      yuklemeTarihi: "2026-04-14",
      gonderiTipi: "FTL",
      gondericiMusteri: "TOPRAK LOJİSTİK A.Ş.",
      aliciMusteri: "AHMET KARAN TİCARET A.Ş.",
      cikisAdres: "Bursa / Osmangazi",
      varisAdres: "İstanbul / Beylikdüzü",
      tedarikciUnvan: "Bedirhan Nakliyat",
      aracPlaka: "16 BDR 001",
      surucu: "Bedirhan Yıldız",
      yukler: [{ yukTipi: "Palet", adet: 10, agirlik: 9600 }],
      yukTipleri: "Palet",
      toplamAdet: 10,
      toplamAgirlik: 9600,
      toplamHacim: 20,
      toplamDesi: 5000,
      alisFiyat: 14500,
      durum: "yolda",
      olusturmaTarihi: "2026-04-13",
      olusturan: "Planlama",
      giderler: [
        {
          id: "gdr-bdr-1-1",
          aciklama: "Taşıma Ücreti",
          tedarikci: "Bedirhan Nakliyat",
          tarih: "2026-04-14",
          birimFiyat: 14500,
          tevkifat: "yok",
          tevfikatTutar: 0,
          kdvOran: 20,
          kdvTutar: 2900,
          toplamTutar: 17400,
          faturaDurumu: "eslestirilmedi",
          odemeDurumu: "bekliyor",
        },
      ],
    },
  ],
}

/* ------------------------------------------------------------------ */
/*  Tedarikçi bazlı fatura & ödeme kayıtları                          */
/* ------------------------------------------------------------------ */

export const supplierFinancialMock: Record<string, SupplierFinancialRecord[]> = {
  /* ── Ekspress24 Kargo (id:1) ── */
  "1": [
    {
      id: "sf-eks-inv-1",
      type: "fatura",
      invoiceNo: "EKS2026000000045",
      description: "Nisan 2026 taşıma hizmeti faturası",
      amount: 46200,
      remainingBalance: 0,
      status: "odendi",
      createdAt: "2026-04-11",
      supplierTitle: "Ekspress24 Kargo",
      category: "Taşıma Hizmeti",
      tag: "Operasyon",
      invoiceDate: "2026-04-11",
      dueDate: "2026-05-11",
      netAmount: 38500,
      vatAmount: 7700,
      totalAmount: 46200,
      paidAmount: 46200,
    },
    {
      id: "sf-eks-pay-1",
      type: "odeme",
      invoiceNo: "HAV-2026-00112",
      description: "EKS2026000000045 fatura ödemesi",
      amount: 46200,
      remainingBalance: 0,
      status: "odendi",
      createdAt: "2026-04-12",
      recipientName: "Ekspress24 Kargo A.Ş.",
      recipientIban: "TR12 0001 0017 0000 0001 2345 67",
      senderName: "ARF LOJİSTİK A.Ş.",
      senderIban: "TR50 0001 0017 0000 0088 8888 88",
      referenceNumber: "HAV-2026-00112",
      paymentMethod: "Havale / EFT",
      direction: "debit",
      matchStatus: "matched",
      matchSource: "manual",
      matchedEntityLabel: "EKS2026000000045",
    },
    {
      id: "sf-eks-inv-2",
      type: "fatura",
      invoiceNo: "EKS2026000000052",
      description: "TSM-20000005 taşıma hizmeti faturası",
      amount: 28200,
      remainingBalance: 28200,
      status: "bekliyor",
      createdAt: "2026-04-16",
      supplierTitle: "Ekspress24 Kargo",
      category: "Taşıma Hizmeti",
      tag: "Operasyon",
      invoiceDate: "2026-04-16",
      dueDate: "2026-05-16",
      netAmount: 23500,
      vatAmount: 4700,
      totalAmount: 28200,
      paidAmount: 0,
    },
  ],
  /* ── Kuzey Lojistik A.Ş. (id:2) ── */
  "2": [
    {
      id: "sf-kzl-inv-1",
      type: "fatura",
      invoiceNo: "KZL2026000000180",
      description: "TSM-20000002 taşıma hizmeti",
      amount: 21576,
      remainingBalance: 0,
      status: "odendi",
      createdAt: "2026-04-09",
      supplierTitle: "Kuzey Lojistik A.Ş.",
      category: "Taşıma Hizmeti",
      tag: "Operasyon",
      invoiceDate: "2026-04-09",
      dueDate: "2026-05-24",
      netAmount: 17980,
      vatAmount: 3596,
      totalAmount: 21576,
      paidAmount: 21576,
    },
    {
      id: "sf-kzl-pay-1",
      type: "odeme",
      invoiceNo: "HAV-2026-00098",
      description: "KZL2026000000180 fatura ödemesi",
      amount: 21576,
      remainingBalance: 0,
      status: "odendi",
      createdAt: "2026-04-15",
      recipientName: "Kuzey Lojistik A.Ş.",
      recipientIban: "TR98 0001 0017 0000 0009 8765 43",
      senderName: "ARF LOJİSTİK A.Ş.",
      senderIban: "TR50 0001 0017 0000 0088 8888 88",
      referenceNumber: "HAV-2026-00098",
      paymentMethod: "Havale / EFT",
      direction: "debit",
      matchStatus: "matched",
      matchSource: "auto",
      matchedEntityLabel: "KZL2026000000180",
    },
    {
      id: "sf-kzl-inv-2",
      type: "fatura",
      invoiceNo: "KZL2026000000195",
      description: "TSM-20000003 taşıma + köprü geçiş",
      amount: 57052.8,
      remainingBalance: 57052.8,
      status: "bekliyor",
      createdAt: "2026-04-13",
      supplierTitle: "Kuzey Lojistik A.Ş.",
      category: "Taşıma Hizmeti",
      tag: "Operasyon",
      invoiceDate: "2026-04-13",
      dueDate: "2026-05-28",
      netAmount: 47544,
      vatAmount: 9508.8,
      totalAmount: 57052.8,
      paidAmount: 0,
    },
  ],
  /* ── Bedirhan Nakliyat (id:4) ── */
  "4": [
    {
      id: "sf-bdr-inv-1",
      type: "fatura",
      invoiceNo: "BDR2026000000012",
      description: "TSM-20000004 taşıma ücreti",
      amount: 17400,
      remainingBalance: 17400,
      status: "bekliyor",
      createdAt: "2026-04-15",
      supplierTitle: "Bedirhan Nakliyat",
      category: "Taşıma Hizmeti",
      tag: "Operasyon",
      invoiceDate: "2026-04-15",
      dueDate: "2026-04-30",
      netAmount: 14500,
      vatAmount: 2900,
      totalAmount: 17400,
      paidAmount: 0,
    },
  ],
}
